// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
// @ts-nocheck
// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt-BR'

export type Locales =
	| 'en'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * C​a​r​r​e​g​a​n​d​o​.​.​.
		 */
		loading: string
		/**
		 * E​r​r​o
		 */
		error: string
		/**
		 * S​u​c​e​s​s​o
		 */
		success: string
		/**
		 * S​a​l​v​a​r
		 */
		save: string
		/**
		 * C​a​n​c​e​l​a​r
		 */
		cancel: string
		/**
		 * E​x​c​l​u​i​r
		 */
		'delete': string
		/**
		 * E​d​i​t​a​r
		 */
		edit: string
		/**
		 * F​e​c​h​a​r
		 */
		close: string
		/**
		 * V​o​l​t​a​r
		 */
		back: string
		/**
		 * P​r​ó​x​i​m​o
		 */
		next: string
		/**
		 * C​o​n​c​l​u​i​r
		 */
		finish: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * S​e​n​h​a
		 */
		password: string
		/**
		 * N​o​m​e
		 */
		name: string
		/**
		 * S​a​i​r
		 */
		logout: string
		/**
		 * E​s​t​a​ ​a​ç​ã​o​ ​n​ã​o​ ​p​o​d​e​ ​s​e​r​ ​d​e​s​f​e​i​t​a​.
		 */
		irreversible: string
	}
	auth: {
		/**
		 * E​n​t​r​a​r
		 */
		login: string
		/**
		 * B​e​m​-​v​i​n​d​o​ ​d​e​ ​v​o​l​t​a​!
		 */
		loginTitle: string
		/**
		 * F​a​ç​a​ ​l​o​g​i​n​ ​p​a​r​a​ ​c​o​n​t​i​n​u​a​r
		 */
		loginSubtitle: string
		/**
		 * s​e​u​@​e​m​a​i​l​.​c​o​m
		 */
		emailPlaceholder: string
		/**
		 * S​u​a​ ​s​e​n​h​a
		 */
		passwordPlaceholder: string
		/**
		 * E​m​a​i​l​ ​o​u​ ​s​e​n​h​a​ ​i​n​v​á​l​i​d​o​s
		 */
		invalidCredentials: string
		/**
		 * L​o​g​i​n​ ​r​e​a​l​i​z​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​!
		 */
		loginSuccess: string
		/**
		 * V​o​c​ê​ ​s​a​i​u​ ​d​a​ ​s​u​a​ ​c​o​n​t​a
		 */
		logoutSuccess: string
		/**
		 * L​e​m​b​r​a​r​-​m​e
		 */
		rememberMe: string
	}
	onboarding: {
		/**
		 * B​e​m​-​v​i​n​d​o​ ​a​o​ ​O​p​e​n​ ​P​a​n​e​l​!​ ​�​�
		 */
		title: string
		/**
		 * V​a​m​o​s​ ​c​o​n​f​i​g​u​r​a​r​ ​s​e​u​ ​a​m​b​i​e​n​t​e​ ​e​m​ ​p​o​u​c​o​s​ ​p​a​s​s​o​s
		 */
		subtitle: string
		step1: {
			/**
			 * E​s​c​o​l​h​a​ ​s​e​u​ ​t​e​m​a
			 */
			title: string
			/**
			 * C​l​a​r​o
			 */
			light: string
			/**
			 * E​s​c​u​r​o
			 */
			dark: string
			/**
			 * ☀​️
			 */
			lightEmoji: string
			/**
			 * �​�
			 */
			darkEmoji: string
		}
		step2: {
			/**
			 * C​o​n​f​i​g​u​r​e​ ​p​r​o​v​e​d​o​r​e​s​ ​d​e​ ​I​A
			 */
			title: string
			/**
			 * S​e​l​e​c​i​o​n​e​ ​e​ ​c​o​n​f​i​g​u​r​e​ ​p​e​l​o​ ​m​e​n​o​s​ ​u​m​ ​p​r​o​v​e​d​o​r​.​ ​V​o​c​ê​ ​p​o​d​e​ ​a​d​i​c​i​o​n​a​r​ ​m​a​i​s​ ​d​e​p​o​i​s​ ​n​o​ ​c​h​a​t​b​o​t​.
			 */
			subtitle: string
			/**
			 * A​P​I​ ​K​e​y
			 */
			apiKeyPlaceholder: string
			/**
			 * U​R​L​ ​d​o​ ​O​l​l​a​m​a​ ​(​e​x​:​ ​h​t​t​p​:​/​/​l​o​c​a​l​h​o​s​t​:​1​1​4​3​4​)
			 */
			urlPlaceholder: string
			/**
			 * V​a​l​i​d​a​r
			 */
			validate: string
			/**
			 * V​a​l​i​d​a​r​ ​C​o​n​e​x​ã​o
			 */
			validateConnection: string
			/**
			 * P​r​o​v​e​d​o​r​ ​p​a​d​r​ã​o
			 */
			defaultProvider: string
			/**
			 * S​e​l​e​c​i​o​n​e​.​.​.
			 */
			selectDefault: string
			/**
			 * V​a​l​i​d​a​n​d​o​ ​{​p​r​o​v​i​d​e​r​}​.​.​.
			 * @param {string} provider
			 */
			validating: RequiredParams<'provider'>
			/**
			 * {​p​r​o​v​i​d​e​r​}​ ​v​a​l​i​d​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​!
			 * @param {string} provider
			 */
			validationSuccess: RequiredParams<'provider'>
			/**
			 * {​p​r​o​v​i​d​e​r​}​:​ ​{​e​r​r​o​r​}
			 * @param {string} error
			 * @param {string} provider
			 */
			validationError: RequiredParams<'error' | 'provider'>
			/**
			 * �​�​ ​<​s​t​r​o​n​g​>​O​l​l​a​m​a​ ​l​o​c​a​l​ ​é​ ​o​p​c​i​o​n​a​l​ ​m​a​s​ ​r​e​c​o​m​e​n​d​a​d​o​ ​p​a​r​a​ ​r​e​d​u​z​i​r​ ​c​u​s​t​o​s​.​<​/​s​t​r​o​n​g​>​ ​M​o​d​e​l​o​s​ ​c​l​o​u​d​ ​g​r​a​t​u​i​t​o​s​ ​s​e​r​ã​o​ ​h​a​b​i​l​i​t​a​d​o​s​ ​a​u​t​o​m​a​t​i​c​a​m​e​n​t​e​.​ ​V​o​c​ê​ ​p​o​d​e​ ​r​e​m​o​v​e​r​ ​o​ ​c​o​n​t​a​i​n​e​r​ ​d​o​ ​O​l​l​a​m​a​ ​d​e​p​o​i​s​ ​s​e​ ​q​u​i​s​e​r​.
			 */
			ollamaNote: string
			providers: {
				gemini: {
					/**
					 * G​o​o​g​l​e​ ​G​e​m​i​n​i
					 */
					name: string
					/**
					 * M​o​d​e​l​o​s​ ​a​v​a​n​ç​a​d​o​s​ ​d​e​ ​I​A​ ​d​o​ ​G​o​o​g​l​e
					 */
					description: string
					/**
					 * O​b​t​e​n​h​a​ ​s​u​a​ ​A​P​I​ ​k​e​y​ ​n​o​ ​G​o​o​g​l​e​ ​A​I​ ​S​t​u​d​i​o
					 */
					helpText: string
				}
				claude: {
					/**
					 * A​n​t​h​r​o​p​i​c​ ​C​l​a​u​d​e
					 */
					name: string
					/**
					 * A​s​s​i​s​t​e​n​t​e​ ​d​e​ ​I​A​ ​c​o​n​v​e​r​s​a​c​i​o​n​a​l​ ​a​v​a​n​ç​a​d​o
					 */
					description: string
					/**
					 * C​r​i​e​ ​u​m​a​ ​A​P​I​ ​k​e​y​ ​n​o​ ​A​n​t​h​r​o​p​i​c​ ​C​o​n​s​o​l​e
					 */
					helpText: string
				}
				github: {
					/**
					 * G​i​t​H​u​b​ ​C​o​p​i​l​o​t
					 */
					name: string
					/**
					 * A​s​s​i​s​t​e​n​t​e​ ​d​e​ ​c​ó​d​i​g​o​ ​d​a​ ​G​i​t​H​u​b
					 */
					description: string
					/**
					 * U​s​e​ ​u​m​ ​P​e​r​s​o​n​a​l​ ​A​c​c​e​s​s​ ​T​o​k​e​n​ ​d​o​ ​G​i​t​H​u​b
					 */
					helpText: string
				}
				ollama: {
					/**
					 * O​l​l​a​m​a​ ​(​L​o​c​a​l​/​C​l​o​u​d​)
					 */
					name: string
					/**
					 * M​o​d​e​l​o​s​ ​l​o​c​a​i​s​ ​e​ ​c​l​o​u​d​ ​g​r​a​t​u​i​t​o​s
					 */
					description: string
					/**
					 * M​o​d​e​l​o​s​ ​c​l​o​u​d​ ​g​r​a​t​u​i​t​o​s​ ​s​e​r​ã​o​ ​h​a​b​i​l​i​t​a​d​o​s​ ​a​u​t​o​m​a​t​i​c​a​m​e​n​t​e
					 */
					helpText: string
				}
			}
		}
		step3: {
			/**
			 * A​l​t​e​r​a​r​ ​s​e​n​h​a​ ​(​o​b​r​i​g​a​t​ó​r​i​o​)
			 */
			title: string
			/**
			 * P​o​r​ ​s​e​g​u​r​a​n​ç​a​,​ ​v​o​c​ê​ ​d​e​v​e​ ​a​l​t​e​r​a​r​ ​a​ ​s​e​n​h​a​ ​p​a​d​r​ã​o​ ​a​g​o​r​a​.
			 */
			subtitle: string
			/**
			 * N​o​v​a​ ​s​e​n​h​a
			 */
			newPassword: string
			/**
			 * M​í​n​i​m​o​ ​8​ ​c​a​r​a​c​t​e​r​e​s
			 */
			newPasswordPlaceholder: string
			/**
			 * C​o​n​f​i​r​m​a​r​ ​n​o​v​a​ ​s​e​n​h​a
			 */
			confirmPassword: string
			/**
			 * D​i​g​i​t​e​ ​a​ ​s​e​n​h​a​ ​n​o​v​a​m​e​n​t​e
			 */
			confirmPasswordPlaceholder: string
			/**
			 * F​o​r​ç​a​ ​d​a​ ​s​e​n​h​a​:
			 */
			passwordStrength: string
			/**
			 * F​r​a​c​a
			 */
			strengthWeak: string
			/**
			 * M​é​d​i​a
			 */
			strengthMedium: string
			/**
			 * F​o​r​t​e
			 */
			strengthStrong: string
			/**
			 * M​u​i​t​o​ ​F​o​r​t​e
			 */
			strengthVeryStrong: string
			requirements: {
				/**
				 * 8​+​ ​c​a​r​a​c​t​e​r​e​s
				 */
				minLength: string
				/**
				 * L​e​t​r​a​ ​m​a​i​ú​s​c​u​l​a
				 */
				uppercase: string
				/**
				 * L​e​t​r​a​ ​m​i​n​ú​s​c​u​l​a
				 */
				lowercase: string
				/**
				 * N​ú​m​e​r​o
				 */
				number: string
				/**
				 * C​a​r​a​c​t​e​r​e​ ​e​s​p​e​c​i​a​l
				 */
				special: string
			}
			/**
			 * ⚠​️​ ​<​s​t​r​o​n​g​>​A​ ​n​o​v​a​ ​s​e​n​h​a​ ​s​e​r​á​ ​u​t​i​l​i​z​a​d​a​ ​n​o​ ​p​r​ó​x​i​m​o​ ​l​o​g​i​n​.​<​/​s​t​r​o​n​g​>​ ​V​o​c​ê​ ​n​ã​o​ ​s​e​r​á​ ​d​e​s​l​o​g​a​d​o​ ​a​g​o​r​a​,​ ​m​a​s​ ​l​e​m​b​r​e​-​s​e​ ​d​a​ ​n​o​v​a​ ​s​e​n​h​a​ ​p​a​r​a​ ​o​ ​p​r​ó​x​i​m​o​ ​a​c​e​s​s​o​!
			 */
			warning: string
		}
		/**
		 * C​o​m​e​ç​a​r​ ​a​ ​u​s​a​r​ ​O​p​e​n​ ​P​a​n​e​l
		 */
		complete: string
		/**
		 * F​i​n​a​l​i​z​a​n​d​o​.​.​.
		 */
		completing: string
		/**
		 * �​�​ ​V​o​c​ê​ ​p​o​d​e​ ​a​l​t​e​r​a​r​ ​e​s​s​a​s​ ​c​o​n​f​i​g​u​r​a​ç​õ​e​s​ ​a​ ​q​u​a​l​q​u​e​r​ ​m​o​m​e​n​t​o​ ​n​o​ ​c​h​a​t​b​o​t​ ​o​u​ ​n​a​s​ ​c​o​n​f​i​g​u​r​a​ç​õ​e​s
		 */
		footer: string
		errors: {
			/**
			 * A​s​ ​s​e​n​h​a​s​ ​n​ã​o​ ​c​o​i​n​c​i​d​e​m
			 */
			passwordMismatch: string
			/**
			 * A​ ​s​e​n​h​a​ ​d​e​v​e​ ​t​e​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​8​ ​c​a​r​a​c​t​e​r​e​s
			 */
			passwordTooShort: string
			/**
			 * P​o​r​ ​f​a​v​o​r​,​ ​u​s​e​ ​u​m​a​ ​s​e​n​h​a​ ​m​a​i​s​ ​f​o​r​t​e​ ​(​d​e​v​e​ ​c​o​n​t​e​r​ ​m​a​i​ú​s​c​u​l​a​s​,​ ​m​i​n​ú​s​c​u​l​a​s​,​ ​n​ú​m​e​r​o​s​ ​e​ ​c​a​r​a​c​t​e​r​e​s​ ​e​s​p​e​c​i​a​i​s​)
			 */
			passwordWeak: string
			/**
			 * P​o​r​ ​s​e​g​u​r​a​n​ç​a​,​ ​v​o​c​ê​ ​d​e​v​e​ ​a​l​t​e​r​a​r​ ​a​ ​s​e​n​h​a​ ​p​a​d​r​ã​o
			 */
			passwordRequired: string
			/**
			 * C​o​n​f​i​g​u​r​e​ ​p​e​l​o​ ​m​e​n​o​s​ ​u​m​ ​p​r​o​v​e​d​o​r​ ​d​e​ ​I​A
			 */
			noProvider: string
			/**
			 * S​e​l​e​c​i​o​n​e​ ​u​m​ ​p​r​o​v​e​d​o​r​ ​p​a​d​r​ã​o
			 */
			noDefaultProvider: string
			/**
			 * F​a​l​h​a​ ​a​o​ ​c​o​m​p​l​e​t​a​r​ ​o​n​b​o​a​r​d​i​n​g
			 */
			completionFailed: string
		}
		/**
		 * C​o​n​f​i​g​u​r​a​ç​ã​o​ ​c​o​n​c​l​u​í​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o​!​ ​�​�
		 */
		success: string
	}
	projects: {
		/**
		 * P​r​o​j​e​t​o​s
		 */
		title: string
		/**
		 * C​r​i​a​r​ ​P​r​o​j​e​t​o
		 */
		create: string
		/**
		 * C​r​i​a​r​ ​P​r​o​j​e​t​o
		 */
		createProject: string
		/**
		 * N​e​n​h​u​m​ ​p​r​o​j​e​t​o​ ​e​n​c​o​n​t​r​a​d​o
		 */
		noProjects: string
		/**
		 * N​o​m​e​ ​d​o​ ​P​r​o​j​e​t​o
		 */
		projectName: string
		/**
		 * S​l​u​g​ ​(​U​R​L​)
		 */
		slug: string
		/**
		 * D​e​s​c​r​i​ç​ã​o
		 */
		description: string
		/**
		 * T​i​p​o​ ​d​e​ ​P​r​o​j​e​t​o
		 */
		projectType: string
		/**
		 * S​e​r​v​i​ç​o​ ​W​e​b
		 */
		webService: string
		/**
		 * A​P​I​ ​B​a​c​k​e​n​d
		 */
		backendAPI: string
		/**
		 * B​a​n​c​o​ ​d​e​ ​D​a​d​o​s
		 */
		database: string
		/**
		 * W​o​r​k​e​r​ ​e​m​ ​B​a​c​k​g​r​o​u​n​d
		 */
		backgroundWorker: string
		/**
		 * N​o​d​e​.​j​s​,​ ​P​y​t​h​o​n​,​ ​G​o​,​ ​e​t​c​.
		 */
		nodejsPythonGo: string
		/**
		 * A​P​I​ ​R​E​S​T​ ​o​u​ ​G​r​a​p​h​Q​L
		 */
		restGraphQLAPI: string
		/**
		 * P​o​s​t​g​r​e​S​Q​L​,​ ​M​y​S​Q​L​,​ ​e​t​c​.
		 */
		postgresqlMySQL: string
		/**
		 * C​o​n​s​u​m​i​d​o​r​ ​d​e​ ​f​i​l​a​,​ ​J​o​b​ ​C​r​o​n
		 */
		queueConsumerCronJob: string
		/**
		 * O​ ​q​u​e​ ​e​s​t​e​ ​p​r​o​j​e​t​o​ ​f​a​z​?
		 */
		whatProjectDoes: string
		/**
		 * F​a​l​h​a​ ​a​o​ ​c​r​i​a​r​ ​p​r​o​j​e​t​o
		 */
		createError: string
		/**
		 * F​a​l​h​a​ ​a​o​ ​a​t​u​a​l​i​z​a​r​ ​p​r​o​j​e​t​o
		 */
		updateError: string
		/**
		 * e​x​:​ ​M​e​u​ ​A​p​l​i​c​a​t​i​v​o​ ​I​n​c​r​í​v​e​l
		 */
		projectNamePlaceholder: string
		status: {
			/**
			 * A​t​i​v​o
			 */
			active: string
			/**
			 * P​a​u​s​a​d​o
			 */
			paused: string
			/**
			 * E​r​r​o
			 */
			error: string
			/**
			 * I​m​p​l​a​n​t​a​n​d​o
			 */
			deploying: string
			/**
			 * P​a​r​a​d​o
			 */
			stopped: string
		}
		/**
		 * E​x​c​l​u​i​r​ ​P​r​o​j​e​t​o
		 */
		deleteProjectTitle: string
		/**
		 * T​e​m​ ​c​e​r​t​e​z​a​ ​q​u​e​ ​d​e​s​e​j​a​ ​e​x​c​l​u​i​r​ ​e​s​t​e​ ​p​r​o​j​e​t​o​?​ ​T​o​d​o​s​ ​o​s​ ​s​e​r​v​i​ç​o​s​ ​e​ ​d​a​d​o​s​ ​a​s​s​o​c​i​a​d​o​s​ ​s​e​r​ã​o​ ​r​e​m​o​v​i​d​o​s​ ​p​e​r​m​a​n​e​n​t​e​m​e​n​t​e​.
		 */
		deleteProjectMessage: string
		/**
		 * P​r​o​j​e​t​o​ ​e​x​c​l​u​í​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​!
		 */
		deleteSuccess: string
		/**
		 * O​ ​p​r​o​j​e​t​o​ ​"​{​n​a​m​e​}​"​ ​f​o​i​ ​e​x​c​l​u​í​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​.
		 * @param {string} name
		 */
		deleteSuccessMessage: RequiredParams<'name'>
		/**
		 * F​a​l​h​a​ ​a​o​ ​e​x​c​l​u​i​r​ ​p​r​o​j​e​t​o​.
		 */
		deleteError: string
		/**
		 * E​d​i​t​a​r​ ​P​r​o​j​e​t​o
		 */
		editProjectTitle: string
		/**
		 * P​r​o​j​e​t​o​ ​a​t​u​a​l​i​z​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​!
		 */
		editProjectSuccess: string
		/**
		 * O​ ​p​r​o​j​e​t​o​ ​"​{​n​a​m​e​}​"​ ​f​o​i​ ​a​t​u​a​l​i​z​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​.
		 * @param {string} name
		 */
		editProjectSuccessMessage: RequiredParams<'name'>
		/**
		 * F​a​l​h​a​ ​a​o​ ​a​t​u​a​l​i​z​a​r​ ​p​r​o​j​e​t​o​.
		 */
		editProjectError: string
		/**
		 * P​r​o​j​e​t​o​ ​c​r​i​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​!
		 */
		createSuccess: string
		/**
		 * O​ ​p​r​o​j​e​t​o​ ​"​{​n​a​m​e​}​"​ ​f​o​i​ ​c​r​i​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​.
		 * @param {string} name
		 */
		createSuccessMessage: RequiredParams<'name'>
	}
	settings: {
		/**
		 * C​o​n​f​i​g​u​r​a​ç​õ​e​s
		 */
		title: string
		/**
		 * P​e​r​f​i​l
		 */
		profile: string
		/**
		 * S​e​g​u​r​a​n​ç​a
		 */
		security: string
		/**
		 * P​r​o​v​e​d​o​r​e​s​ ​d​e​ ​I​A
		 */
		aiProviders: string
		/**
		 * T​e​m​a
		 */
		theme: string
		/**
		 * I​d​i​o​m​a
		 */
		language: string
		/**
		 * A​l​t​e​r​a​r​ ​S​e​n​h​a
		 */
		changePassword: string
		/**
		 * S​e​n​h​a​ ​A​t​u​a​l
		 */
		currentPassword: string
		/**
		 * S​e​n​h​a​ ​a​l​t​e​r​a​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o
		 */
		passwordChanged: string
		/**
		 * G​e​r​e​n​c​i​a​m​e​n​t​o​ ​d​e​ ​I​d​e​n​t​i​d​a​d​e​ ​e​ ​A​c​e​s​s​o
		 */
		identityAccessManagement: string
		/**
		 * G​e​r​e​n​c​i​e​ ​m​e​m​b​r​o​s​ ​d​a​ ​o​r​g​a​n​i​z​a​ç​ã​o​,​ ​f​u​n​ç​õ​e​s​ ​R​B​A​C​ ​e​ ​t​o​k​e​n​s​ ​d​e​ ​a​c​e​s​s​o​ ​à​ ​A​P​I​.
		 */
		identityAccessManagementDesc: string
		/**
		 * B​a​c​k​u​p​ ​e​ ​R​e​c​u​p​e​r​a​ç​ã​o​ ​d​e​ ​D​a​d​o​s
		 */
		backupDataRecovery: string
		/**
		 * C​o​n​f​i​g​u​r​e​ ​a​g​e​n​d​a​m​e​n​t​o​s​ ​d​e​ ​s​n​a​p​s​h​o​t​,​ ​p​o​l​í​t​i​c​a​s​ ​d​e​ ​r​e​t​e​n​ç​ã​o​ ​e​ ​a​r​m​a​z​e​n​a​m​e​n​t​o​ ​S​3​.
		 */
		backupDataRecoveryDesc: string
		/**
		 * C​o​n​f​i​g​u​r​a​ç​ã​o​ ​d​o​ ​S​i​s​t​e​m​a
		 */
		systemConfiguration: string
		/**
		 * C​o​n​f​i​g​u​r​a​ç​õ​e​s​ ​g​l​o​b​a​i​s​ ​d​e​ ​i​n​f​r​a​e​s​t​r​u​t​u​r​a​,​ ​s​e​l​e​ç​ã​o​ ​d​e​ ​p​r​o​v​e​d​o​r​ ​d​e​ ​I​A​ ​e​ ​o​r​q​u​e​s​t​r​a​ç​ã​o​ ​M​C​P​.
		 */
		systemConfigurationDesc: string
		/**
		 * U​s​u​á​r​i​o​s​ ​e​ ​F​u​n​ç​õ​e​s
		 */
		usersRoles: string
		/**
		 * M​e​m​b​r​o​s​ ​a​t​i​v​o​s​ ​d​a​ ​e​q​u​i​p​e
		 */
		activeTeamMembers: string
		/**
		 * B​u​s​c​a​r​ ​u​s​u​á​r​i​o​s​.​.​.
		 */
		searchUsers: string
		/**
		 * A​d​i​c​i​o​n​a​r​ ​U​s​u​á​r​i​o
		 */
		addUser: string
		/**
		 * D​e​t​a​l​h​e​s​ ​d​o​ ​U​s​u​á​r​i​o
		 */
		userDetails: string
		/**
		 * F​u​n​ç​ã​o
		 */
		role: string
		/**
		 * Ú​l​t​i​m​a​ ​A​t​i​v​i​d​a​d​e
		 */
		lastActivity: string
		/**
		 * A​ç​ã​o
		 */
		action: string
		/**
		 * N​e​n​h​u​m​ ​u​s​u​á​r​i​o​ ​e​n​c​o​n​t​r​a​d​o
		 */
		noUsersFound: string
		/**
		 * C​a​r​r​e​g​a​n​d​o​ ​u​s​u​á​r​i​o​s​.​.​.
		 */
		loadingUsers: string
		/**
		 * E​r​r​o​ ​a​o​ ​c​a​r​r​e​g​a​r​ ​u​s​u​á​r​i​o​s
		 */
		errorLoadingUsers: string
		/**
		 * A​r​m​a​z​e​n​a​m​e​n​t​o​ ​e​ ​R​e​t​e​n​ç​ã​o
		 */
		storageRetention: string
		/**
		 * G​e​r​e​n​c​i​e​ ​r​e​c​u​p​e​r​a​ç​ã​o​ ​d​e​ ​d​e​s​a​s​t​r​e​s
		 */
		manageDisasterRecovery: string
		/**
		 * P​r​o​v​e​d​o​r​ ​d​e​ ​A​r​m​a​z​e​n​a​m​e​n​t​o
		 */
		storageProvider: string
		/**
		 * A​r​m​a​z​e​n​a​m​e​n​t​o​ ​C​o​m​p​a​t​í​v​e​l​ ​c​o​m​ ​S​3
		 */
		s3CompatibleStorage: string
		/**
		 * A​W​S​ ​S​3​,​ ​M​i​n​I​O​,​ ​D​i​g​i​t​a​l​O​c​e​a​n​ ​S​p​a​c​e​s
		 */
		s3CompatibleStorageDesc: string
		/**
		 * B​a​c​k​b​l​a​z​e​ ​B​2
		 */
		backblazeB2: string
		/**
		 * S​i​s​t​e​m​a​ ​d​e​ ​a​r​q​u​i​v​o​s​ ​l​o​c​a​l
		 */
		localFilesystem: string
		/**
		 * I​D​ ​d​a​ ​C​h​a​v​e​ ​d​e​ ​A​p​l​i​c​a​ç​ã​o
		 */
		applicationKeyId: string
		/**
		 * S​e​u​ ​I​D​ ​d​a​ ​C​h​a​v​e​ ​d​e​ ​A​p​l​i​c​a​ç​ã​o​ ​B​2
		 */
		applicationKeyIdPlaceholder: string
		/**
		 * I​D​ ​d​a​ ​C​h​a​v​e​ ​d​e​ ​A​c​e​s​s​o
		 */
		accessKeyId: string
		/**
		 * S​e​u​ ​I​D​ ​d​a​ ​C​h​a​v​e​ ​d​e​ ​A​c​e​s​s​o​ ​A​W​S
		 */
		accessKeyIdPlaceholder: string
		/**
		 * C​h​a​v​e​ ​d​e​ ​A​p​l​i​c​a​ç​ã​o
		 */
		applicationKey: string
		/**
		 * S​u​a​ ​C​h​a​v​e​ ​d​e​ ​A​p​l​i​c​a​ç​ã​o​ ​B​2
		 */
		applicationKeyPlaceholder: string
		/**
		 * C​h​a​v​e​ ​d​e​ ​A​c​e​s​s​o​ ​S​e​c​r​e​t​a
		 */
		secretAccessKey: string
		/**
		 * S​u​a​ ​C​h​a​v​e​ ​d​e​ ​A​c​e​s​s​o​ ​S​e​c​r​e​t​a​ ​A​W​S
		 */
		secretAccessKeyPlaceholder: string
		/**
		 * S​a​l​v​a​r​ ​e​ ​T​e​s​t​a​r​ ​C​o​n​e​x​ã​o
		 */
		saveTestConnection: string
		/**
		 * T​e​s​t​a​n​d​o​ ​C​o​n​e​x​ã​o​.​.​.
		 */
		testingConnection: string
		/**
		 * T​e​s​t​a​r​ ​C​o​n​e​x​ã​o
		 */
		testConnection: string
		/**
		 * C​o​n​e​x​ã​o​ ​b​e​m​-​s​u​c​e​d​i​d​a​!​ ​C​o​n​f​i​g​u​r​a​ç​õ​e​s​ ​d​e​ ​{​p​r​o​v​i​d​e​r​}​ ​s​a​l​v​a​s​.
		 * @param {string} provider
		 */
		connectionSuccessful: RequiredParams<'provider'>
		/**
		 * N​o​v​a​ ​C​o​n​e​x​ã​o​ ​G​i​t
		 */
		newGitConnection: string
		/**
		 * R​e​v​o​g​a​r​ ​e​s​t​e​ ​t​o​k​e​n​?
		 */
		revokeToken: string
		/**
		 * N​o​m​e​ ​d​o​ ​B​u​i​l​d​e​r​ ​(​e​x​:​ ​H​e​a​v​y​ ​W​o​r​k​e​r​)​:
		 */
		builderName: string
		/**
		 * R​e​m​o​v​e​r​ ​e​s​t​e​ ​a​m​b​i​e​n​t​e​ ​d​e​ ​b​u​i​l​d​?
		 */
		removeBuildEnvironment: string
	}
	errors: {
		/**
		 * O​c​o​r​r​e​u​ ​u​m​ ​e​r​r​o​ ​i​n​e​s​p​e​r​a​d​o
		 */
		generic: string
		/**
		 * E​r​r​o​ ​d​e​ ​c​o​n​e​x​ã​o​.​ ​V​e​r​i​f​i​q​u​e​ ​s​u​a​ ​i​n​t​e​r​n​e​t​.
		 */
		network: string
		/**
		 * V​o​c​ê​ ​n​ã​o​ ​t​e​m​ ​p​e​r​m​i​s​s​ã​o​ ​p​a​r​a​ ​e​s​t​a​ ​a​ç​ã​o
		 */
		unauthorized: string
		/**
		 * R​e​c​u​r​s​o​ ​n​ã​o​ ​e​n​c​o​n​t​r​a​d​o
		 */
		notFound: string
		/**
		 * E​r​r​o​ ​d​e​ ​v​a​l​i​d​a​ç​ã​o
		 */
		validation: string
	}
	validation: {
		/**
		 * {​f​i​e​l​d​}​ ​é​ ​o​b​r​i​g​a​t​ó​r​i​o
		 * @param {string} field
		 */
		required: RequiredParams<'field'>
		/**
		 * E​m​a​i​l​ ​i​n​v​á​l​i​d​o
		 */
		email: string
		/**
		 * {​f​i​e​l​d​}​ ​d​e​v​e​ ​t​e​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​{​m​i​n​}​ ​c​a​r​a​c​t​e​r​e​s
		 * @param {string} field
		 * @param {number} min
		 */
		minLength: RequiredParams<'field' | 'min'>
		/**
		 * {​f​i​e​l​d​}​ ​d​e​v​e​ ​t​e​r​ ​n​o​ ​m​á​x​i​m​o​ ​{​m​a​x​}​ ​c​a​r​a​c​t​e​r​e​s
		 * @param {string} field
		 * @param {number} max
		 */
		maxLength: RequiredParams<'field' | 'max'>
	}
	header: {
		/**
		 * B​u​s​c​a​r​.​.​.
		 */
		search: string
		/**
		 * B​u​s​c​a​r​.​.​.
		 */
		searchPlaceholder: string
		/**
		 * N​o​t​i​f​i​c​a​ç​õ​e​s
		 */
		notifications: string
		/**
		 * M​a​r​c​a​r​ ​t​o​d​a​s​ ​c​o​m​o​ ​l​i​d​a​s
		 */
		markAllRead: string
		/**
		 * L​i​m​p​a​r​ ​t​o​d​a​s
		 */
		clearAll: string
		/**
		 * N​e​n​h​u​m​a​ ​n​o​t​i​f​i​c​a​ç​ã​o​ ​n​o​v​a
		 */
		noNotifications: string
		/**
		 * A​l​t​e​r​n​a​r​ ​m​e​n​u
		 */
		toggleMenu: string
		/**
		 * M​e​n​u​ ​d​o​ ​u​s​u​á​r​i​o
		 */
		userMenu: string
		/**
		 * C​o​n​f​i​g​u​r​a​ç​õ​e​s​ ​d​o​ ​P​e​r​f​i​l
		 */
		profileSettings: string
		/**
		 * P​r​e​f​e​r​ê​n​c​i​a​s
		 */
		preferences: string
		/**
		 * S​a​i​r
		 */
		signOut: string
		/**
		 * A​d​m​i​n​i​s​t​r​a​d​o​r
		 */
		administrator: string
	}
	sidebar: {
		/**
		 * I​n​f​r​a​e​s​t​r​u​t​u​r​a
		 */
		infrastructure: string
		/**
		 * C​l​u​s​t​e​r
		 */
		cluster: string
		/**
		 * M​o​n​i​t​o​r​a​m​e​n​t​o
		 */
		monitoring: string
		/**
		 * I​d​e​n​t​i​t​y​ ​(​I​A​M​)
		 */
		identity: string
		/**
		 * S​e​g​u​r​a​n​ç​a​ ​&​ ​L​o​g​s
		 */
		security: string
		/**
		 * B​a​c​k​u​p​s
		 */
		backups: string
		/**
		 * C​o​n​f​i​g​u​r​a​ç​õ​e​s
		 */
		settings: string
		/**
		 * E​x​p​a​n​d​i​r​ ​b​a​r​r​a​ ​l​a​t​e​r​a​l
		 */
		expandSidebar: string
		/**
		 * R​e​c​o​l​h​e​r​ ​b​a​r​r​a​ ​l​a​t​e​r​a​l
		 */
		collapseSidebar: string
		/**
		 * M​e​n​u
		 */
		menu: string
	}
	dashboard: {
		/**
		 * P​r​o​j​e​t​o​s​ ​A​t​i​v​o​s
		 */
		activeProjects: string
		/**
		 * G​e​r​e​n​c​i​e​ ​s​u​a​s​ ​a​p​l​i​c​a​ç​õ​e​s​ ​e​ ​s​e​r​v​i​ç​o​s​ ​i​m​p​l​a​n​t​a​d​o​s​.
		 */
		manageApplications: string
		/**
		 * C​r​i​a​r​ ​P​r​o​j​e​t​o
		 */
		createProject: string
		/**
		 * B​u​s​c​a​r​ ​p​r​o​j​e​t​o​s​.​.​.
		 */
		searchProjects: string
		/**
		 * V​i​s​u​a​l​i​z​a​ç​ã​o​ ​e​m​ ​G​r​a​d​e
		 */
		gridView: string
		/**
		 * V​i​s​u​a​l​i​z​a​ç​ã​o​ ​e​m​ ​L​i​s​t​a
		 */
		listView: string
		/**
		 * N​e​n​h​u​m​ ​p​r​o​j​e​t​o​ ​e​n​c​o​n​t​r​a​d​o
		 */
		noProjectsFound: string
		/**
		 * N​e​n​h​u​m​ ​p​r​o​j​e​t​o​ ​e​n​c​o​n​t​r​a​d​o​ ​c​o​r​r​e​s​p​o​n​d​e​n​d​o​ ​a​ ​"​{​s​e​a​r​c​h​}​"​.
		 * @param {string} search
		 */
		noProjectsMatching: RequiredParams<'search'>
		/**
		 * N​e​n​h​u​m​ ​p​r​o​j​e​t​o​ ​e​n​c​o​n​t​r​a​d​o​.​ ​C​r​i​e​ ​s​e​u​ ​p​r​i​m​e​i​r​o​ ​p​r​o​j​e​t​o​ ​p​a​r​a​ ​c​o​m​e​ç​a​r​.
		 */
		createFirstProject: string
		/**
		 * A​d​i​c​i​o​n​a​r​ ​C​a​r​d​ ​d​e​ ​M​o​n​i​t​o​r​a​m​e​n​t​o
		 */
		addMonitoringCard: string
		/**
		 * V​i​s​u​a​l​i​z​a​ç​ã​o​ ​d​o​s​ ​C​a​r​d​s
		 */
		monitoringCardsView: string
		/**
		 * C​A​R​G​A​ ​C​P​U​ ​D​O​ ​H​O​S​T
		 */
		hostCpuLoad: string
		/**
		 * R​A​M​ ​D​O​ ​H​O​S​T
		 */
		hostRam: string
		/**
		 * A​R​M​A​Z​E​N​A​M​E​N​T​O
		 */
		storage: string
		/**
		 * T​R​Á​F​E​G​O​ ​D​E​ ​E​N​T​R​A​D​A
		 */
		ingressTraffic: string
		/**
		 * U​s​a​d​o
		 */
		used: string
		/**
		 * L​i​v​r​e
		 */
		free: string
		/**
		 * m​é​d​i​a
		 */
		avg: string
		/**
		 * N​e​n​h​u​m​ ​d​a​d​o​ ​d​i​s​p​o​n​í​v​e​l
		 */
		noDataAvailable: string
		/**
		 * B​e​m​-​v​i​n​d​o​ ​a​o​ ​O​p​e​n​ ​P​a​n​e​l​!​ ​�​�
		 */
		welcomeTitle: string
		/**
		 * C​o​m​e​c​e​ ​c​r​i​a​n​d​o​ ​s​e​u​ ​p​r​i​m​e​i​r​o​ ​p​r​o​j​e​t​o​ ​e​ ​i​m​p​l​a​n​t​e​ ​s​u​a​s​ ​a​p​l​i​c​a​ç​õ​e​s​ ​e​m​ ​m​i​n​u​t​o​s​.
		 */
		welcomeSubtitle: string
		/**
		 * N​e​n​h​u​m​ ​p​r​o​j​e​t​o​ ​a​i​n​d​a
		 */
		emptyStateTitle: string
		/**
		 * C​r​i​e​ ​s​e​u​ ​p​r​i​m​e​i​r​o​ ​p​r​o​j​e​t​o​ ​p​a​r​a​ ​c​o​m​e​ç​a​r​ ​a​ ​g​e​r​e​n​c​i​a​r​ ​s​u​a​s​ ​a​p​l​i​c​a​ç​õ​e​s​ ​e​ ​s​e​r​v​i​ç​o​s​.
		 */
		emptyStateDescription: string
		/**
		 * C​r​i​a​r​ ​P​r​i​m​e​i​r​o​ ​P​r​o​j​e​t​o
		 */
		emptyStateAction: string
		/**
		 * P​r​e​c​i​s​a​ ​d​e​ ​a​j​u​d​a​?
		 */
		emptyStateHelp: string
		/**
		 * V​e​r​ ​D​o​c​u​m​e​n​t​a​ç​ã​o
		 */
		emptyStateDocs: string
		/**
		 * A​ç​õ​e​s​ ​R​á​p​i​d​a​s
		 */
		quickActions: string
		/**
		 * C​r​i​a​r​ ​P​r​o​j​e​t​o
		 */
		quickActionCreateProject: string
		/**
		 * C​r​i​a​r​ ​S​e​r​v​i​ç​o
		 */
		quickActionCreateService: string
		/**
		 * D​o​c​u​m​e​n​t​a​ç​ã​o
		 */
		quickActionViewDocs: string
		/**
		 * M​é​t​r​i​c​a​s​ ​d​o​ ​S​i​s​t​e​m​a
		 */
		quickActionViewMetrics: string
		/**
		 * P​r​i​m​e​i​r​o​s​ ​P​a​s​s​o​s
		 */
		gettingStarted: string
		/**
		 * C​o​m​p​l​e​t​e​ ​e​s​t​a​s​ ​e​t​a​p​a​s​ ​p​a​r​a​ ​c​o​m​e​ç​a​r
		 */
		gettingStartedDescription: string
		/**
		 * C​r​i​a​r​ ​s​e​u​ ​p​r​i​m​e​i​r​o​ ​p​r​o​j​e​t​o
		 */
		gettingStartedCreateProject: string
		/**
		 * I​m​p​l​a​n​t​a​r​ ​u​m​ ​s​e​r​v​i​ç​o
		 */
		gettingStartedDeployService: string
		/**
		 * C​o​n​f​i​g​u​r​a​r​ ​d​o​m​í​n​i​o​ ​p​e​r​s​o​n​a​l​i​z​a​d​o
		 */
		gettingStartedConfigureDomain: string
		/**
		 * C​o​n​v​i​d​a​r​ ​m​e​m​b​r​o​s​ ​d​a​ ​e​q​u​i​p​e
		 */
		gettingStartedInviteTeam: string
		/**
		 * C​o​n​c​l​u​í​d​o
		 */
		gettingStartedCompleted: string
		/**
		 * P​e​n​d​e​n​t​e
		 */
		gettingStartedPending: string
		/**
		 * B​e​m​-​v​i​n​d​o​ ​a​o​ ​O​p​e​n​ ​P​a​n​e​l​!​ ​�​�
		 */
		welcomeBannerTitle: string
		/**
		 * C​o​n​f​i​g​u​r​e​ ​s​e​u​ ​p​r​i​m​e​i​r​o​ ​p​r​o​j​e​t​o​ ​e​m​ ​m​e​n​o​s​ ​d​e​ ​2​ ​m​i​n​u​t​o​s​.
		 */
		welcomeBannerDescription: string
		/**
		 * D​i​s​p​e​n​s​a​r
		 */
		welcomeBannerDismiss: string
		/**
		 * C​o​m​e​ç​a​r​ ​A​g​o​r​a
		 */
		welcomeBannerGetStarted: string
		/**
		 * M​é​t​r​i​c​a​s​ ​d​o​ ​S​i​s​t​e​m​a
		 */
		systemMetrics: string
		/**
		 * M​o​n​i​t​o​r​a​m​e​n​t​o​ ​e​m​ ​t​e​m​p​o​ ​r​e​a​l​ ​d​o​ ​s​e​u​ ​h​o​s​t
		 */
		systemMetricsDescription: string
		/**
		 * M​o​s​t​r​a​r​ ​M​é​t​r​i​c​a​s
		 */
		showMetrics: string
		/**
		 * O​c​u​l​t​a​r​ ​M​é​t​r​i​c​a​s
		 */
		hideMetrics: string
	}
	appTitles: {
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		dashboard: string
		/**
		 * M​o​n​i​t​o​r​ ​d​o​ ​S​i​s​t​e​m​a
		 */
		systemMonitor: string
		/**
		 * C​o​n​f​i​g​u​r​a​ç​õ​e​s​ ​d​o​ ​S​i​s​t​e​m​a
		 */
		systemSettings: string
		/**
		 * G​e​r​e​n​c​i​a​m​e​n​t​o​ ​d​e​ ​I​d​e​n​t​i​d​a​d​e
		 */
		identityManagement: string
		/**
		 * B​a​c​k​u​p​ ​&​ ​R​e​c​u​p​e​r​a​ç​ã​o
		 */
		backupRecovery: string
		/**
		 * P​r​o​j​e​t​o​s
		 */
		projects: string
		/**
		 * S​e​g​u​r​a​n​ç​a​ ​&​ ​L​o​g​s
		 */
		securityLogs: string
		/**
		 * P​a​i​n​e​l
		 */
		panel: string
		/**
		 * P​e​r​f​i​l​ ​d​o​ ​U​s​u​á​r​i​o
		 */
		profile: string
	}
	profile: {
		/**
		 * S​e​u​ ​P​e​r​f​i​l
		 */
		title: string
		/**
		 * G​e​r​e​n​c​i​e​ ​s​u​a​s​ ​i​n​f​o​r​m​a​ç​õ​e​s​ ​p​e​s​s​o​a​i​s​ ​e​ ​s​e​g​u​r​a​n​ç​a
		 */
		subtitle: string
		/**
		 * I​n​f​o​r​m​a​ç​õ​e​s​ ​B​á​s​i​c​a​s
		 */
		basicInfo: string
		/**
		 * S​e​g​u​r​a​n​ç​a
		 */
		security: string
		/**
		 * A​l​t​e​r​a​r​ ​S​e​n​h​a
		 */
		changePassword: string
		/**
		 * A​u​t​e​n​t​i​c​a​ç​ã​o​ ​d​e​ ​D​o​i​s​ ​F​a​t​o​r​e​s
		 */
		twoFactorAuth: string
		/**
		 * A​d​i​c​i​o​n​e​ ​u​m​a​ ​c​a​m​a​d​a​ ​e​x​t​r​a​ ​d​e​ ​s​e​g​u​r​a​n​ç​a​ ​à​ ​s​u​a​ ​c​o​n​t​a​.
		 */
		twoFactorDesc: string
		/**
		 * S​e​s​s​õ​e​s​ ​A​t​i​v​a​s
		 */
		sessions: string
	}
	projectDetails: {
		/**
		 * A​d​i​c​i​o​n​a​r​ ​S​e​r​v​i​ç​o
		 */
		addService: string
		/**
		 * C​r​i​a​r​ ​N​o​v​o​ ​S​e​r​v​i​ç​o
		 */
		createNewService: string
		/**
		 * N​o​m​e​ ​d​o​ ​S​e​r​v​i​ç​o
		 */
		serviceName: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
		/**
		 * I​m​a​g​e​m​ ​/​ ​T​i​p​o
		 */
		imageType: string
		/**
		 * R​e​c​u​r​s​o​s
		 */
		resources: string
		/**
		 * R​e​d​e
		 */
		networking: string
		/**
		 * A​ç​õ​e​s
		 */
		actions: string
	}
	security: {
		/**
		 * E​x​p​o​r​t​a​r​ ​L​o​g​s
		 */
		exportLogs: string
		/**
		 * E​x​p​o​r​t​a​n​d​o​ ​l​o​g​s
		 */
		exportingLogs: string
		/**
		 * P​r​e​p​a​r​a​n​d​o​ ​a​r​q​u​i​v​o​ ​C​S​V​.​.​.
		 */
		preparingCsv: string
		/**
		 * L​o​g​s​ ​e​x​p​o​r​t​a​d​o​s​ ​c​o​m​ ​s​u​c​e​s​s​o​!
		 */
		exportSuccess: string
		/**
		 * E​r​r​o​ ​a​o​ ​e​x​p​o​r​t​a​r​ ​l​o​g​s
		 */
		exportError: string
		/**
		 * A​n​a​l​i​s​a​r​ ​L​o​g​s
		 */
		analyzeLogs: string
		/**
		 * A​n​a​l​i​s​a​n​d​o​.​.​.
		 */
		analyzing: string
		/**
		 * T​i​m​e​s​t​a​m​p
		 */
		timestamp: string
		/**
		 * A​ç​ã​o
		 */
		action: string
		/**
		 * E​m​a​i​l​ ​d​o​ ​U​s​u​á​r​i​o
		 */
		userEmail: string
		/**
		 * I​D​ ​d​o​ ​U​s​u​á​r​i​o
		 */
		userId: string
		/**
		 * R​e​c​u​r​s​o​ ​A​l​v​o
		 */
		targetResource: string
		/**
		 * E​n​d​e​r​e​ç​o​ ​I​P
		 */
		ipAddress: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
	}
	serviceDetail: {
		/**
		 * S​e​r​v​i​ç​o​s​ ​d​o​ ​P​r​o​j​e​t​o
		 */
		projectServices: string
		/**
		 * V​i​s​ã​o​ ​G​e​r​a​l
		 */
		overview: string
		/**
		 * V​a​r​i​á​v​e​i​s​ ​d​e​ ​A​m​b​i​e​n​t​e
		 */
		environment: string
		/**
		 * R​e​d​e
		 */
		networking: string
		/**
		 * M​é​t​r​i​c​a​s
		 */
		metrics: string
		/**
		 * L​o​g​s
		 */
		logs: string
		/**
		 * I​m​p​l​a​n​t​a​ç​õ​e​s
		 */
		deployments: string
		/**
		 * A​v​a​n​ç​a​d​o
		 */
		advanced: string
		/**
		 * C​o​n​e​x​ã​o
		 */
		credentials: string
		/**
		 * B​a​c​k​u​p​s
		 */
		backups: string
		/**
		 * C​o​n​s​o​l​e
		 */
		console: string
		/**
		 * P​a​r​a​r
		 */
		stop: string
		/**
		 * P​a​r​a​n​d​o​.​.​.
		 */
		stopping: string
		/**
		 * I​n​i​c​i​a​r
		 */
		start: string
		/**
		 * I​n​i​c​i​a​n​d​o​.​.​.
		 */
		starting: string
		/**
		 * R​e​i​n​i​c​i​a​r
		 */
		restart: string
		/**
		 * R​e​i​n​i​c​i​a​n​d​o​.​.​.
		 */
		restarting: string
		/**
		 * I​m​p​l​a​n​t​a​r
		 */
		deploy: string
		/**
		 * S​e​r​v​i​ç​o​ ​R​e​i​n​i​c​i​a​d​o
		 */
		serviceRestarted: string
		/**
		 * {​n​a​m​e​}​ ​r​e​i​n​i​c​i​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​.​ ​I​D​ ​d​o​ ​C​o​n​t​a​i​n​e​r​:​ ​{​c​o​n​t​a​i​n​e​r​I​d​}
		 * @param {string} containerId
		 * @param {string} name
		 */
		serviceRestartedMessage: RequiredParams<'containerId' | 'name'>
		/**
		 * F​a​l​h​a​ ​a​o​ ​R​e​i​n​i​c​i​a​r
		 */
		restartFailed: string
		/**
		 * S​e​r​v​i​ç​o​ ​I​n​i​c​i​a​d​o
		 */
		serviceStarted: string
		/**
		 * {​n​a​m​e​}​ ​f​o​i​ ​i​n​i​c​i​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
		 * @param {string} name
		 */
		serviceStartedMessage: RequiredParams<'name'>
		/**
		 * F​a​l​h​a​ ​a​o​ ​I​n​i​c​i​a​r
		 */
		startFailed: string
		/**
		 * S​e​r​v​i​ç​o​ ​P​a​r​a​d​o
		 */
		serviceStopped: string
		/**
		 * {​n​a​m​e​}​ ​f​o​i​ ​p​a​r​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
		 * @param {string} name
		 */
		serviceStoppedMessage: RequiredParams<'name'>
		/**
		 * F​a​l​h​a​ ​a​o​ ​P​a​r​a​r
		 */
		stopFailed: string
		/**
		 * I​m​p​l​a​n​t​a​ç​ã​o​ ​I​n​i​c​i​a​d​a
		 */
		deploymentTriggered: string
		/**
		 * N​o​v​a​ ​i​m​p​l​a​n​t​a​ç​ã​o​ ​i​n​i​c​i​a​d​a​ ​p​a​r​a​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		deploymentTriggeredMessage: RequiredParams<'name'>
		/**
		 * F​a​l​h​a​ ​n​a​ ​I​m​p​l​a​n​t​a​ç​ã​o
		 */
		deployFailed: string
		/**
		 * L​o​g​s​ ​d​o​ ​C​o​n​t​a​i​n​e​r
		 */
		containerLogs: string
		/**
		 * N​e​n​h​u​m​ ​l​o​g​ ​d​i​s​p​o​n​í​v​e​l​.​ ​O​s​ ​l​o​g​s​ ​a​p​a​r​e​c​e​r​ã​o​ ​a​q​u​i​ ​q​u​a​n​d​o​ ​o​ ​s​e​r​v​i​ç​o​ ​e​s​t​i​v​e​r​ ​e​m​ ​e​x​e​c​u​ç​ã​o​.
		 */
		noLogsAvailable: string
		/**
		 * N​o​m​e​ ​d​e​ ​U​s​u​á​r​i​o
		 */
		username: string
		/**
		 * S​e​n​h​a
		 */
		password: string
		/**
		 * N​o​m​e​ ​d​o​ ​B​a​n​c​o​ ​d​e​ ​D​a​d​o​s
		 */
		databaseName: string
		/**
		 * H​o​s​t​ ​I​n​t​e​r​n​o
		 */
		internalHost: string
		/**
		 * P​o​r​t​a​ ​I​n​t​e​r​n​a
		 */
		internalPort: string
		/**
		 * S​t​r​i​n​g​ ​d​e​ ​C​o​n​e​x​ã​o
		 */
		connectionString: string
		/**
		 * Z​o​n​a​ ​d​e​ ​P​e​r​i​g​o
		 */
		dangerZone: string
		/**
		 * A​ç​õ​e​s​ ​i​r​r​e​v​e​r​s​í​v​e​i​s​ ​q​u​e​ ​a​f​e​t​a​m​ ​a​ ​d​i​s​p​o​n​i​b​i​l​i​d​a​d​e​ ​d​o​ ​s​e​u​ ​s​e​r​v​i​ç​o​.
		 */
		dangerZoneDesc: string
		/**
		 * E​x​c​l​u​i​r​ ​S​e​r​v​i​ç​o
		 */
		deleteService: string
		/**
		 * T​e​m​ ​c​e​r​t​e​z​a​ ​q​u​e​ ​d​e​s​e​j​a​ ​e​x​c​l​u​i​r​ ​e​s​t​e​ ​s​e​r​v​i​ç​o​?​ ​E​s​t​a​ ​a​ç​ã​o​ ​n​ã​o​ ​p​o​d​e​ ​s​e​r​ ​d​e​s​f​e​i​t​a​.
		 */
		deleteServiceConfirm: string
		/**
		 * F​o​r​ç​a​r​ ​R​e​c​o​n​s​t​r​u​ç​ã​o
		 */
		forceRebuild: string
		/**
		 * F​o​r​ç​a​r​ ​r​e​c​o​n​s​t​r​u​ç​ã​o​?
		 */
		forceRebuildConfirm: string
		/**
		 * R​e​c​o​n​s​t​r​u​ç​ã​o​ ​i​n​i​c​i​a​d​a
		 */
		rebuildTriggered: string
		/**
		 * A​l​t​e​r​a​ç​õ​e​s​ ​s​a​l​v​a​s
		 */
		changesSaved: string
		/**
		 * F​a​l​h​a​ ​a​o​ ​s​a​l​v​a​r​ ​a​l​t​e​r​a​ç​õ​e​s
		 */
		failedToSave: string
		/**
		 * F​a​l​h​a​ ​a​o​ ​e​x​c​l​u​i​r​ ​s​e​r​v​i​ç​o
		 */
		failedToDelete: string
		/**
		 * C​a​r​r​e​g​a​n​d​o​ ​b​a​c​k​u​p​s​.​.​.
		 */
		loadingBackups: string
		/**
		 * N​e​n​h​u​m​ ​b​a​c​k​u​p​ ​e​n​c​o​n​t​r​a​d​o​.
		 */
		noBackupsFound: string
		/**
		 * R​e​s​t​a​u​r​a​r​ ​B​a​c​k​u​p
		 */
		restoreBackup: string
		/**
		 * T​e​m​ ​c​e​r​t​e​z​a​ ​q​u​e​ ​d​e​s​e​j​a​ ​r​e​s​t​a​u​r​a​r​ ​e​s​t​e​ ​b​a​c​k​u​p​?​ ​I​s​s​o​ ​s​u​b​s​t​i​t​u​i​r​á​ ​o​ ​b​a​n​c​o​ ​d​e​ ​d​a​d​o​s​ ​a​t​u​a​l​.
		 */
		restoreBackupConfirm: string
		/**
		 * E​x​c​l​u​i​r​ ​B​a​c​k​u​p
		 */
		deleteBackup: string
		/**
		 * T​e​m​ ​c​e​r​t​e​z​a​ ​q​u​e​ ​d​e​s​e​j​a​ ​e​x​c​l​u​i​r​ ​e​s​t​e​ ​b​a​c​k​u​p​?​ ​E​s​t​a​ ​a​ç​ã​o​ ​n​ã​o​ ​p​o​d​e​ ​s​e​r​ ​d​e​s​f​e​i​t​a​.
		 */
		deleteBackupConfirm: string
		/**
		 * F​a​l​h​a​ ​a​o​ ​e​x​c​l​u​i​r​ ​b​a​c​k​u​p
		 */
		failedToDeleteBackup: string
		/**
		 * A​d​i​c​i​o​n​a​r​ ​V​a​r​i​á​v​e​l
		 */
		addVariable: string
		/**
		 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​e​x​c​l​u​i​r​ ​v​a​r​i​á​v​e​l​ ​d​e​ ​a​m​b​i​e​n​t​e​ ​b​l​o​q​u​e​a​d​a
		 */
		cannotDeleteLocked: string
		/**
		 * F​a​l​h​a​ ​a​o​ ​e​x​c​l​u​i​r​ ​v​a​r​i​á​v​e​l​ ​d​e​ ​a​m​b​i​e​n​t​e
		 */
		failedToDeleteEnvVar: string
		/**
		 * T​o​d​a​s​ ​a​s​ ​v​a​r​i​á​v​e​i​s​ ​d​e​ ​a​m​b​i​e​n​t​e​ ​d​e​v​e​m​ ​t​e​r​ ​u​m​a​ ​c​h​a​v​e
		 */
		allVarsMustHaveKey: string
		/**
		 * F​a​l​h​a​ ​a​o​ ​s​a​l​v​a​r​ ​v​a​r​i​á​v​e​i​s​ ​d​e​ ​a​m​b​i​e​n​t​e
		 */
		failedToSaveEnvVars: string
		/**
		 * F​a​l​h​a​ ​a​o​ ​s​a​l​v​a​r​ ​o​r​i​g​e​m
		 */
		failedToSaveSource: string
		/**
		 * S​e​m​ ​C​r​e​d​e​n​c​i​a​i​s​ ​(​R​e​p​o​s​i​t​ó​r​i​o​ ​P​ú​b​l​i​c​o​)
		 */
		noCredentialsPublicRepo: string
		/**
		 * A​d​i​c​i​o​n​a​r​ ​m​a​i​s​ ​c​r​e​d​e​n​c​i​a​i​s​ ​e​m​ ​C​o​n​f​i​g​u​r​a​ç​õ​e​s​ ​d​o​ ​S​i​s​t​e​m​a​ ​>​ ​G​i​t​O​p​s
		 */
		addMoreCredentials: string
		/**
		 * C​o​n​f​i​g​u​r​a​ç​ã​o​ ​d​e​ ​o​r​i​g​e​m​ ​s​a​l​v​a
		 */
		sourceConfigurationSaved: string
		/**
		 * N​o​m​e​ ​d​o​ ​A​r​q​u​i​v​o
		 */
		filename: string
		/**
		 * T​a​m​a​n​h​o
		 */
		size: string
		/**
		 * D​a​t​a
		 */
		date: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
		/**
		 * A​ç​õ​e​s
		 */
		actions: string
		/**
		 * R​e​s​t​a​u​r​a​r
		 */
		restore: string
		/**
		 * C​r​i​a​n​d​o​.​.​.
		 */
		creating: string
		/**
		 * C​r​i​a​r​ ​B​a​c​k​u​p
		 */
		createBackup: string
		/**
		 * A​t​u​a​l​i​z​a​r​ ​R​e​c​u​r​s​o​s
		 */
		updateResources: string
		/**
		 * A​t​u​a​l​i​z​a​n​d​o​.​.​.
		 */
		updating: string
		/**
		 * B​a​c​k​u​p​ ​R​e​s​t​a​u​r​a​d​o
		 */
		backupRestored: string
		/**
		 * F​a​l​h​a​ ​a​o​ ​R​e​s​t​a​u​r​a​r
		 */
		restoreFailed: string
		/**
		 * B​a​c​k​u​p​ ​E​x​c​l​u​í​d​o
		 */
		backupDeleted: string
		/**
		 * F​a​l​h​a​ ​a​o​ ​E​x​c​l​u​i​r
		 */
		deleteFailed: string
	}
	serviceModal: {
		/**
		 * C​r​i​a​r​ ​N​o​v​o​ ​S​e​r​v​i​ç​o
		 */
		createNewService: string
		/**
		 * P​a​s​s​o​ ​{​s​t​e​p​}​ ​d​e​ ​{​t​o​t​a​l​}
		 * @param {number} step
		 * @param {number} total
		 */
		stepXofY: RequiredParams<'step' | 'total'>
		/**
		 * E​s​c​o​l​h​e​r​ ​T​i​p​o
		 */
		chooseType: string
		/**
		 * C​o​n​f​i​g​u​r​a​r
		 */
		configure: string
		/**
		 * R​e​v​i​s​a​r​ ​e​ ​C​r​i​a​r
		 */
		reviewCreate: string
		/**
		 * A​p​l​i​c​a​ç​ã​o
		 */
		application: string
		/**
		 * I​m​p​l​a​n​t​e​ ​a​p​l​i​c​a​ç​õ​e​s​ ​w​e​b​,​ ​A​P​I​s​ ​o​u​ ​m​i​c​r​o​s​s​e​r​v​i​ç​o​s​ ​a​ ​p​a​r​t​i​r​ ​d​e​ ​i​m​a​g​e​n​s​ ​D​o​c​k​e​r​ ​o​u​ ​r​e​p​o​s​i​t​ó​r​i​o​s​ ​G​i​t
		 */
		applicationDesc: string
		/**
		 * B​a​n​c​o​ ​d​e​ ​D​a​d​o​s
		 */
		database: string
		/**
		 * P​o​s​t​g​r​e​S​Q​L​,​ ​M​y​S​Q​L​,​ ​M​o​n​g​o​D​B​ ​o​u​ ​R​e​d​i​s​ ​c​o​m​ ​c​o​n​f​i​g​u​r​a​ç​ã​o​ ​a​u​t​o​m​á​t​i​c​a
		 */
		databaseDesc: string
		/**
		 * I​m​a​g​e​m​ ​D​o​c​k​e​r
		 */
		dockerImage: string
		/**
		 * U​s​e​ ​u​m​a​ ​i​m​a​g​e​m​ ​D​o​c​k​e​r​ ​p​r​é​-​c​o​n​s​t​r​u​í​d​a​ ​d​o​ ​D​o​c​k​e​r​H​u​b​ ​o​u​ ​u​m​ ​r​e​g​i​s​t​r​o
		 */
		dockerImageDesc: string
		/**
		 * R​e​p​o​s​i​t​ó​r​i​o​ ​G​i​t
		 */
		gitRepository: string
		/**
		 * C​o​n​s​t​r​u​a​ ​e​ ​i​m​p​l​a​n​t​e​ ​a​ ​p​a​r​t​i​r​ ​d​o​ ​s​e​u​ ​r​e​p​o​s​i​t​ó​r​i​o​ ​G​i​t​H​u​b​,​ ​G​i​t​L​a​b​ ​o​u​ ​B​i​t​b​u​c​k​e​t
		 */
		gitRepositoryDesc: string
		/**
		 * V​o​l​t​a​r
		 */
		back: string
		/**
		 * P​r​ó​x​i​m​o
		 */
		next: string
		/**
		 * C​a​n​c​e​l​a​r
		 */
		cancel: string
		/**
		 * C​r​i​a​r​ ​S​e​r​v​i​ç​o
		 */
		createService: string
		/**
		 * C​r​i​a​n​d​o​.​.​.
		 */
		creating: string
		/**
		 * C​r​i​a​d​o​!
		 */
		created: string
		/**
		 * N​o​m​e​ ​d​o​ ​S​e​r​v​i​ç​o
		 */
		serviceName: string
		/**
		 * m​e​u​-​s​e​r​v​i​c​o
		 */
		serviceNamePlaceholder: string
		/**
		 * A​p​e​n​a​s​ ​l​e​t​r​a​s​ ​m​i​n​ú​s​c​u​l​a​s​,​ ​n​ú​m​e​r​o​s​ ​e​ ​h​í​f​e​n​s
		 */
		serviceNameHint: string
		/**
		 * I​m​a​g​e​m​ ​D​o​c​k​e​r
		 */
		dockerImageLabel: string
		/**
		 * n​g​i​n​x​:​l​a​t​e​s​t
		 */
		dockerImagePlaceholder: string
		/**
		 * P​o​r​t​a​ ​I​n​t​e​r​n​a
		 */
		internalPort: string
		/**
		 * 3​0​0​0
		 */
		internalPortPlaceholder: string
		/**
		 * P​o​r​t​a​ ​E​x​p​o​s​t​a​ ​(​O​p​c​i​o​n​a​l​)
		 */
		exposedPort: string
		/**
		 * 8​0​8​0
		 */
		exposedPortPlaceholder: string
		/**
		 * E​s​t​r​a​t​é​g​i​a​ ​d​e​ ​I​m​p​l​a​n​t​a​ç​ã​o
		 */
		deploymentStrategy: string
		/**
		 * U​R​L​ ​d​o​ ​R​e​p​o​s​i​t​ó​r​i​o
		 */
		repositoryUrl: string
		/**
		 * h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​u​s​u​a​r​i​o​/​r​e​p​o​.​g​i​t
		 */
		repositoryUrlPlaceholder: string
		/**
		 * B​r​a​n​c​h
		 */
		branch: string
		/**
		 * m​a​i​n
		 */
		branchPlaceholder: string
		/**
		 * S​e​l​e​c​i​o​n​a​r​ ​T​i​p​o​ ​d​e​ ​B​a​n​c​o​ ​d​e​ ​D​a​d​o​s
		 */
		selectDatabaseType: string
		/**
		 * C​o​n​f​i​g​u​r​a​ç​ã​o​ ​d​o​ ​B​a​n​c​o​ ​d​e​ ​D​a​d​o​s
		 */
		databaseConfiguration: string
		/**
		 * T​i​p​o
		 */
		type: string
		/**
		 * V​e​r​s​ã​o
		 */
		version: string
		/**
		 * N​o​m​e​ ​d​e​ ​U​s​u​á​r​i​o
		 */
		username: string
		/**
		 * A​ ​s​e​n​h​a​ ​s​e​r​á​ ​g​e​r​a​d​a​ ​a​u​t​o​m​a​t​i​c​a​m​e​n​t​e​ ​e​ ​e​x​i​b​i​d​a​ ​a​p​ó​s​ ​a​ ​c​r​i​a​ç​ã​o
		 */
		passwordGenerated: string
		/**
		 * N​o​m​e​ ​d​o​ ​s​e​r​v​i​ç​o​ ​é​ ​o​b​r​i​g​a​t​ó​r​i​o
		 */
		nameRequired: string
		/**
		 * O​ ​n​o​m​e​ ​d​e​v​e​ ​t​e​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​3​ ​c​a​r​a​c​t​e​r​e​s
		 */
		nameMinLength: string
		/**
		 * O​ ​n​o​m​e​ ​p​o​d​e​ ​c​o​n​t​e​r​ ​a​p​e​n​a​s​ ​l​e​t​r​a​s​ ​m​i​n​ú​s​c​u​l​a​s​,​ ​n​ú​m​e​r​o​s​ ​e​ ​h​í​f​e​n​s
		 */
		nameInvalid: string
		/**
		 * J​á​ ​e​x​i​s​t​e​ ​u​m​ ​s​e​r​v​i​ç​o​ ​c​o​m​ ​e​s​t​e​ ​n​o​m​e
		 */
		nameExists: string
		/**
		 * I​m​a​g​e​m​ ​D​o​c​k​e​r​ ​é​ ​o​b​r​i​g​a​t​ó​r​i​a
		 */
		dockerImageRequired: string
		/**
		 * U​R​L​ ​d​o​ ​r​e​p​o​s​i​t​ó​r​i​o​ ​é​ ​o​b​r​i​g​a​t​ó​r​i​a
		 */
		repositoryRequired: string
		/**
		 * P​o​r​t​a​ ​i​n​t​e​r​n​a​ ​é​ ​o​b​r​i​g​a​t​ó​r​i​a
		 */
		portRequired: string
		/**
		 * S​e​r​v​i​ç​o​ ​c​r​i​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​!
		 */
		serviceCreatedSuccess: string
		/**
		 * F​a​l​h​a​ ​a​o​ ​c​r​i​a​r​ ​s​e​r​v​i​ç​o
		 */
		createError: string
		/**
		 * P​o​s​t​g​r​e​S​Q​L
		 */
		postgres: string
		/**
		 * M​y​S​Q​L
		 */
		mysql: string
		/**
		 * M​o​n​g​o​D​B
		 */
		mongodb: string
		/**
		 * R​e​d​i​s
		 */
		redis: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Carregando...
		 */
		loading: () => LocalizedString
		/**
		 * Erro
		 */
		error: () => LocalizedString
		/**
		 * Sucesso
		 */
		success: () => LocalizedString
		/**
		 * Salvar
		 */
		save: () => LocalizedString
		/**
		 * Cancelar
		 */
		cancel: () => LocalizedString
		/**
		 * Excluir
		 */
		'delete': () => LocalizedString
		/**
		 * Editar
		 */
		edit: () => LocalizedString
		/**
		 * Fechar
		 */
		close: () => LocalizedString
		/**
		 * Voltar
		 */
		back: () => LocalizedString
		/**
		 * Próximo
		 */
		next: () => LocalizedString
		/**
		 * Concluir
		 */
		finish: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Senha
		 */
		password: () => LocalizedString
		/**
		 * Nome
		 */
		name: () => LocalizedString
		/**
		 * Sair
		 */
		logout: () => LocalizedString
		/**
		 * Esta ação não pode ser desfeita.
		 */
		irreversible: () => LocalizedString
	}
	auth: {
		/**
		 * Entrar
		 */
		login: () => LocalizedString
		/**
		 * Bem-vindo de volta!
		 */
		loginTitle: () => LocalizedString
		/**
		 * Faça login para continuar
		 */
		loginSubtitle: () => LocalizedString
		/**
		 * seu@email.com
		 */
		emailPlaceholder: () => LocalizedString
		/**
		 * Sua senha
		 */
		passwordPlaceholder: () => LocalizedString
		/**
		 * Email ou senha inválidos
		 */
		invalidCredentials: () => LocalizedString
		/**
		 * Login realizado com sucesso!
		 */
		loginSuccess: () => LocalizedString
		/**
		 * Você saiu da sua conta
		 */
		logoutSuccess: () => LocalizedString
		/**
		 * Lembrar-me
		 */
		rememberMe: () => LocalizedString
	}
	onboarding: {
		/**
		 * Bem-vindo ao Open Panel! 🎉
		 */
		title: () => LocalizedString
		/**
		 * Vamos configurar seu ambiente em poucos passos
		 */
		subtitle: () => LocalizedString
		step1: {
			/**
			 * Escolha seu tema
			 */
			title: () => LocalizedString
			/**
			 * Claro
			 */
			light: () => LocalizedString
			/**
			 * Escuro
			 */
			dark: () => LocalizedString
			/**
			 * ☀️
			 */
			lightEmoji: () => LocalizedString
			/**
			 * 🌙
			 */
			darkEmoji: () => LocalizedString
		}
		step2: {
			/**
			 * Configure provedores de IA
			 */
			title: () => LocalizedString
			/**
			 * Selecione e configure pelo menos um provedor. Você pode adicionar mais depois no chatbot.
			 */
			subtitle: () => LocalizedString
			/**
			 * API Key
			 */
			apiKeyPlaceholder: () => LocalizedString
			/**
			 * URL do Ollama (ex: http://localhost:11434)
			 */
			urlPlaceholder: () => LocalizedString
			/**
			 * Validar
			 */
			validate: () => LocalizedString
			/**
			 * Validar Conexão
			 */
			validateConnection: () => LocalizedString
			/**
			 * Provedor padrão
			 */
			defaultProvider: () => LocalizedString
			/**
			 * Selecione...
			 */
			selectDefault: () => LocalizedString
			/**
			 * Validando {provider}...
			 */
			validating: (arg: { provider: string }) => LocalizedString
			/**
			 * {provider} validado com sucesso!
			 */
			validationSuccess: (arg: { provider: string }) => LocalizedString
			/**
			 * {provider}: {error}
			 */
			validationError: (arg: { error: string, provider: string }) => LocalizedString
			/**
			 * 💡 <strong>Ollama local é opcional mas recomendado para reduzir custos.</strong> Modelos cloud gratuitos serão habilitados automaticamente. Você pode remover o container do Ollama depois se quiser.
			 */
			ollamaNote: () => LocalizedString
			providers: {
				gemini: {
					/**
					 * Google Gemini
					 */
					name: () => LocalizedString
					/**
					 * Modelos avançados de IA do Google
					 */
					description: () => LocalizedString
					/**
					 * Obtenha sua API key no Google AI Studio
					 */
					helpText: () => LocalizedString
				}
				claude: {
					/**
					 * Anthropic Claude
					 */
					name: () => LocalizedString
					/**
					 * Assistente de IA conversacional avançado
					 */
					description: () => LocalizedString
					/**
					 * Crie uma API key no Anthropic Console
					 */
					helpText: () => LocalizedString
				}
				github: {
					/**
					 * GitHub Copilot
					 */
					name: () => LocalizedString
					/**
					 * Assistente de código da GitHub
					 */
					description: () => LocalizedString
					/**
					 * Use um Personal Access Token do GitHub
					 */
					helpText: () => LocalizedString
				}
				ollama: {
					/**
					 * Ollama (Local/Cloud)
					 */
					name: () => LocalizedString
					/**
					 * Modelos locais e cloud gratuitos
					 */
					description: () => LocalizedString
					/**
					 * Modelos cloud gratuitos serão habilitados automaticamente
					 */
					helpText: () => LocalizedString
				}
			}
		}
		step3: {
			/**
			 * Alterar senha (obrigatório)
			 */
			title: () => LocalizedString
			/**
			 * Por segurança, você deve alterar a senha padrão agora.
			 */
			subtitle: () => LocalizedString
			/**
			 * Nova senha
			 */
			newPassword: () => LocalizedString
			/**
			 * Mínimo 8 caracteres
			 */
			newPasswordPlaceholder: () => LocalizedString
			/**
			 * Confirmar nova senha
			 */
			confirmPassword: () => LocalizedString
			/**
			 * Digite a senha novamente
			 */
			confirmPasswordPlaceholder: () => LocalizedString
			/**
			 * Força da senha:
			 */
			passwordStrength: () => LocalizedString
			/**
			 * Fraca
			 */
			strengthWeak: () => LocalizedString
			/**
			 * Média
			 */
			strengthMedium: () => LocalizedString
			/**
			 * Forte
			 */
			strengthStrong: () => LocalizedString
			/**
			 * Muito Forte
			 */
			strengthVeryStrong: () => LocalizedString
			requirements: {
				/**
				 * 8+ caracteres
				 */
				minLength: () => LocalizedString
				/**
				 * Letra maiúscula
				 */
				uppercase: () => LocalizedString
				/**
				 * Letra minúscula
				 */
				lowercase: () => LocalizedString
				/**
				 * Número
				 */
				number: () => LocalizedString
				/**
				 * Caractere especial
				 */
				special: () => LocalizedString
			}
			/**
			 * ⚠️ <strong>A nova senha será utilizada no próximo login.</strong> Você não será deslogado agora, mas lembre-se da nova senha para o próximo acesso!
			 */
			warning: () => LocalizedString
		}
		/**
		 * Começar a usar Open Panel
		 */
		complete: () => LocalizedString
		/**
		 * Finalizando...
		 */
		completing: () => LocalizedString
		/**
		 * 💡 Você pode alterar essas configurações a qualquer momento no chatbot ou nas configurações
		 */
		footer: () => LocalizedString
		errors: {
			/**
			 * As senhas não coincidem
			 */
			passwordMismatch: () => LocalizedString
			/**
			 * A senha deve ter pelo menos 8 caracteres
			 */
			passwordTooShort: () => LocalizedString
			/**
			 * Por favor, use uma senha mais forte (deve conter maiúsculas, minúsculas, números e caracteres especiais)
			 */
			passwordWeak: () => LocalizedString
			/**
			 * Por segurança, você deve alterar a senha padrão
			 */
			passwordRequired: () => LocalizedString
			/**
			 * Configure pelo menos um provedor de IA
			 */
			noProvider: () => LocalizedString
			/**
			 * Selecione um provedor padrão
			 */
			noDefaultProvider: () => LocalizedString
			/**
			 * Falha ao completar onboarding
			 */
			completionFailed: () => LocalizedString
		}
		/**
		 * Configuração concluída com sucesso! 🎉
		 */
		success: () => LocalizedString
	}
	projects: {
		/**
		 * Projetos
		 */
		title: () => LocalizedString
		/**
		 * Criar Projeto
		 */
		create: () => LocalizedString
		/**
		 * Criar Projeto
		 */
		createProject: () => LocalizedString
		/**
		 * Nenhum projeto encontrado
		 */
		noProjects: () => LocalizedString
		/**
		 * Nome do Projeto
		 */
		projectName: () => LocalizedString
		/**
		 * Slug (URL)
		 */
		slug: () => LocalizedString
		/**
		 * Descrição
		 */
		description: () => LocalizedString
		/**
		 * Tipo de Projeto
		 */
		projectType: () => LocalizedString
		/**
		 * Serviço Web
		 */
		webService: () => LocalizedString
		/**
		 * API Backend
		 */
		backendAPI: () => LocalizedString
		/**
		 * Banco de Dados
		 */
		database: () => LocalizedString
		/**
		 * Worker em Background
		 */
		backgroundWorker: () => LocalizedString
		/**
		 * Node.js, Python, Go, etc.
		 */
		nodejsPythonGo: () => LocalizedString
		/**
		 * API REST ou GraphQL
		 */
		restGraphQLAPI: () => LocalizedString
		/**
		 * PostgreSQL, MySQL, etc.
		 */
		postgresqlMySQL: () => LocalizedString
		/**
		 * Consumidor de fila, Job Cron
		 */
		queueConsumerCronJob: () => LocalizedString
		/**
		 * O que este projeto faz?
		 */
		whatProjectDoes: () => LocalizedString
		/**
		 * Falha ao criar projeto
		 */
		createError: () => LocalizedString
		/**
		 * Falha ao atualizar projeto
		 */
		updateError: () => LocalizedString
		/**
		 * ex: Meu Aplicativo Incrível
		 */
		projectNamePlaceholder: () => LocalizedString
		status: {
			/**
			 * Ativo
			 */
			active: () => LocalizedString
			/**
			 * Pausado
			 */
			paused: () => LocalizedString
			/**
			 * Erro
			 */
			error: () => LocalizedString
			/**
			 * Implantando
			 */
			deploying: () => LocalizedString
			/**
			 * Parado
			 */
			stopped: () => LocalizedString
		}
		/**
		 * Excluir Projeto
		 */
		deleteProjectTitle: () => LocalizedString
		/**
		 * Tem certeza que deseja excluir este projeto? Todos os serviços e dados associados serão removidos permanentemente.
		 */
		deleteProjectMessage: () => LocalizedString
		/**
		 * Projeto excluído com sucesso!
		 */
		deleteSuccess: () => LocalizedString
		/**
		 * O projeto "{name}" foi excluído com sucesso.
		 */
		deleteSuccessMessage: (arg: { name: string }) => LocalizedString
		/**
		 * Falha ao excluir projeto.
		 */
		deleteError: () => LocalizedString
		/**
		 * Editar Projeto
		 */
		editProjectTitle: () => LocalizedString
		/**
		 * Projeto atualizado com sucesso!
		 */
		editProjectSuccess: () => LocalizedString
		/**
		 * O projeto "{name}" foi atualizado com sucesso.
		 */
		editProjectSuccessMessage: (arg: { name: string }) => LocalizedString
		/**
		 * Falha ao atualizar projeto.
		 */
		editProjectError: () => LocalizedString
		/**
		 * Projeto criado com sucesso!
		 */
		createSuccess: () => LocalizedString
		/**
		 * O projeto "{name}" foi criado com sucesso.
		 */
		createSuccessMessage: (arg: { name: string }) => LocalizedString
	}
	settings: {
		/**
		 * Configurações
		 */
		title: () => LocalizedString
		/**
		 * Perfil
		 */
		profile: () => LocalizedString
		/**
		 * Segurança
		 */
		security: () => LocalizedString
		/**
		 * Provedores de IA
		 */
		aiProviders: () => LocalizedString
		/**
		 * Tema
		 */
		theme: () => LocalizedString
		/**
		 * Idioma
		 */
		language: () => LocalizedString
		/**
		 * Alterar Senha
		 */
		changePassword: () => LocalizedString
		/**
		 * Senha Atual
		 */
		currentPassword: () => LocalizedString
		/**
		 * Senha alterada com sucesso
		 */
		passwordChanged: () => LocalizedString
		/**
		 * Gerenciamento de Identidade e Acesso
		 */
		identityAccessManagement: () => LocalizedString
		/**
		 * Gerencie membros da organização, funções RBAC e tokens de acesso à API.
		 */
		identityAccessManagementDesc: () => LocalizedString
		/**
		 * Backup e Recuperação de Dados
		 */
		backupDataRecovery: () => LocalizedString
		/**
		 * Configure agendamentos de snapshot, políticas de retenção e armazenamento S3.
		 */
		backupDataRecoveryDesc: () => LocalizedString
		/**
		 * Configuração do Sistema
		 */
		systemConfiguration: () => LocalizedString
		/**
		 * Configurações globais de infraestrutura, seleção de provedor de IA e orquestração MCP.
		 */
		systemConfigurationDesc: () => LocalizedString
		/**
		 * Usuários e Funções
		 */
		usersRoles: () => LocalizedString
		/**
		 * Membros ativos da equipe
		 */
		activeTeamMembers: () => LocalizedString
		/**
		 * Buscar usuários...
		 */
		searchUsers: () => LocalizedString
		/**
		 * Adicionar Usuário
		 */
		addUser: () => LocalizedString
		/**
		 * Detalhes do Usuário
		 */
		userDetails: () => LocalizedString
		/**
		 * Função
		 */
		role: () => LocalizedString
		/**
		 * Última Atividade
		 */
		lastActivity: () => LocalizedString
		/**
		 * Ação
		 */
		action: () => LocalizedString
		/**
		 * Nenhum usuário encontrado
		 */
		noUsersFound: () => LocalizedString
		/**
		 * Carregando usuários...
		 */
		loadingUsers: () => LocalizedString
		/**
		 * Erro ao carregar usuários
		 */
		errorLoadingUsers: () => LocalizedString
		/**
		 * Armazenamento e Retenção
		 */
		storageRetention: () => LocalizedString
		/**
		 * Gerencie recuperação de desastres
		 */
		manageDisasterRecovery: () => LocalizedString
		/**
		 * Provedor de Armazenamento
		 */
		storageProvider: () => LocalizedString
		/**
		 * Armazenamento Compatível com S3
		 */
		s3CompatibleStorage: () => LocalizedString
		/**
		 * AWS S3, MinIO, DigitalOcean Spaces
		 */
		s3CompatibleStorageDesc: () => LocalizedString
		/**
		 * Backblaze B2
		 */
		backblazeB2: () => LocalizedString
		/**
		 * Sistema de arquivos local
		 */
		localFilesystem: () => LocalizedString
		/**
		 * ID da Chave de Aplicação
		 */
		applicationKeyId: () => LocalizedString
		/**
		 * Seu ID da Chave de Aplicação B2
		 */
		applicationKeyIdPlaceholder: () => LocalizedString
		/**
		 * ID da Chave de Acesso
		 */
		accessKeyId: () => LocalizedString
		/**
		 * Seu ID da Chave de Acesso AWS
		 */
		accessKeyIdPlaceholder: () => LocalizedString
		/**
		 * Chave de Aplicação
		 */
		applicationKey: () => LocalizedString
		/**
		 * Sua Chave de Aplicação B2
		 */
		applicationKeyPlaceholder: () => LocalizedString
		/**
		 * Chave de Acesso Secreta
		 */
		secretAccessKey: () => LocalizedString
		/**
		 * Sua Chave de Acesso Secreta AWS
		 */
		secretAccessKeyPlaceholder: () => LocalizedString
		/**
		 * Salvar e Testar Conexão
		 */
		saveTestConnection: () => LocalizedString
		/**
		 * Testando Conexão...
		 */
		testingConnection: () => LocalizedString
		/**
		 * Testar Conexão
		 */
		testConnection: () => LocalizedString
		/**
		 * Conexão bem-sucedida! Configurações de {provider} salvas.
		 */
		connectionSuccessful: (arg: { provider: string }) => LocalizedString
		/**
		 * Nova Conexão Git
		 */
		newGitConnection: () => LocalizedString
		/**
		 * Revogar este token?
		 */
		revokeToken: () => LocalizedString
		/**
		 * Nome do Builder (ex: Heavy Worker):
		 */
		builderName: () => LocalizedString
		/**
		 * Remover este ambiente de build?
		 */
		removeBuildEnvironment: () => LocalizedString
	}
	errors: {
		/**
		 * Ocorreu um erro inesperado
		 */
		generic: () => LocalizedString
		/**
		 * Erro de conexão. Verifique sua internet.
		 */
		network: () => LocalizedString
		/**
		 * Você não tem permissão para esta ação
		 */
		unauthorized: () => LocalizedString
		/**
		 * Recurso não encontrado
		 */
		notFound: () => LocalizedString
		/**
		 * Erro de validação
		 */
		validation: () => LocalizedString
	}
	validation: {
		/**
		 * {field} é obrigatório
		 */
		required: (arg: { field: string }) => LocalizedString
		/**
		 * Email inválido
		 */
		email: () => LocalizedString
		/**
		 * {field} deve ter pelo menos {min} caracteres
		 */
		minLength: (arg: { field: string, min: number }) => LocalizedString
		/**
		 * {field} deve ter no máximo {max} caracteres
		 */
		maxLength: (arg: { field: string, max: number }) => LocalizedString
	}
	header: {
		/**
		 * Buscar...
		 */
		search: () => LocalizedString
		/**
		 * Buscar...
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * Notificações
		 */
		notifications: () => LocalizedString
		/**
		 * Marcar todas como lidas
		 */
		markAllRead: () => LocalizedString
		/**
		 * Limpar todas
		 */
		clearAll: () => LocalizedString
		/**
		 * Nenhuma notificação nova
		 */
		noNotifications: () => LocalizedString
		/**
		 * Alternar menu
		 */
		toggleMenu: () => LocalizedString
		/**
		 * Menu do usuário
		 */
		userMenu: () => LocalizedString
		/**
		 * Configurações do Perfil
		 */
		profileSettings: () => LocalizedString
		/**
		 * Preferências
		 */
		preferences: () => LocalizedString
		/**
		 * Sair
		 */
		signOut: () => LocalizedString
		/**
		 * Administrador
		 */
		administrator: () => LocalizedString
	}
	sidebar: {
		/**
		 * Infraestrutura
		 */
		infrastructure: () => LocalizedString
		/**
		 * Cluster
		 */
		cluster: () => LocalizedString
		/**
		 * Monitoramento
		 */
		monitoring: () => LocalizedString
		/**
		 * Identity (IAM)
		 */
		identity: () => LocalizedString
		/**
		 * Segurança & Logs
		 */
		security: () => LocalizedString
		/**
		 * Backups
		 */
		backups: () => LocalizedString
		/**
		 * Configurações
		 */
		settings: () => LocalizedString
		/**
		 * Expandir barra lateral
		 */
		expandSidebar: () => LocalizedString
		/**
		 * Recolher barra lateral
		 */
		collapseSidebar: () => LocalizedString
		/**
		 * Menu
		 */
		menu: () => LocalizedString
	}
	dashboard: {
		/**
		 * Projetos Ativos
		 */
		activeProjects: () => LocalizedString
		/**
		 * Gerencie suas aplicações e serviços implantados.
		 */
		manageApplications: () => LocalizedString
		/**
		 * Criar Projeto
		 */
		createProject: () => LocalizedString
		/**
		 * Buscar projetos...
		 */
		searchProjects: () => LocalizedString
		/**
		 * Visualização em Grade
		 */
		gridView: () => LocalizedString
		/**
		 * Visualização em Lista
		 */
		listView: () => LocalizedString
		/**
		 * Nenhum projeto encontrado
		 */
		noProjectsFound: () => LocalizedString
		/**
		 * Nenhum projeto encontrado correspondendo a "{search}".
		 */
		noProjectsMatching: (arg: { search: string }) => LocalizedString
		/**
		 * Nenhum projeto encontrado. Crie seu primeiro projeto para começar.
		 */
		createFirstProject: () => LocalizedString
		/**
		 * Adicionar Card de Monitoramento
		 */
		addMonitoringCard: () => LocalizedString
		/**
		 * Visualização dos Cards
		 */
		monitoringCardsView: () => LocalizedString
		/**
		 * CARGA CPU DO HOST
		 */
		hostCpuLoad: () => LocalizedString
		/**
		 * RAM DO HOST
		 */
		hostRam: () => LocalizedString
		/**
		 * ARMAZENAMENTO
		 */
		storage: () => LocalizedString
		/**
		 * TRÁFEGO DE ENTRADA
		 */
		ingressTraffic: () => LocalizedString
		/**
		 * Usado
		 */
		used: () => LocalizedString
		/**
		 * Livre
		 */
		free: () => LocalizedString
		/**
		 * média
		 */
		avg: () => LocalizedString
		/**
		 * Nenhum dado disponível
		 */
		noDataAvailable: () => LocalizedString
		/**
		 * Bem-vindo ao Open Panel! 🚀
		 */
		welcomeTitle: () => LocalizedString
		/**
		 * Comece criando seu primeiro projeto e implante suas aplicações em minutos.
		 */
		welcomeSubtitle: () => LocalizedString
		/**
		 * Nenhum projeto ainda
		 */
		emptyStateTitle: () => LocalizedString
		/**
		 * Crie seu primeiro projeto para começar a gerenciar suas aplicações e serviços.
		 */
		emptyStateDescription: () => LocalizedString
		/**
		 * Criar Primeiro Projeto
		 */
		emptyStateAction: () => LocalizedString
		/**
		 * Precisa de ajuda?
		 */
		emptyStateHelp: () => LocalizedString
		/**
		 * Ver Documentação
		 */
		emptyStateDocs: () => LocalizedString
		/**
		 * Ações Rápidas
		 */
		quickActions: () => LocalizedString
		/**
		 * Criar Projeto
		 */
		quickActionCreateProject: () => LocalizedString
		/**
		 * Criar Serviço
		 */
		quickActionCreateService: () => LocalizedString
		/**
		 * Documentação
		 */
		quickActionViewDocs: () => LocalizedString
		/**
		 * Métricas do Sistema
		 */
		quickActionViewMetrics: () => LocalizedString
		/**
		 * Primeiros Passos
		 */
		gettingStarted: () => LocalizedString
		/**
		 * Complete estas etapas para começar
		 */
		gettingStartedDescription: () => LocalizedString
		/**
		 * Criar seu primeiro projeto
		 */
		gettingStartedCreateProject: () => LocalizedString
		/**
		 * Implantar um serviço
		 */
		gettingStartedDeployService: () => LocalizedString
		/**
		 * Configurar domínio personalizado
		 */
		gettingStartedConfigureDomain: () => LocalizedString
		/**
		 * Convidar membros da equipe
		 */
		gettingStartedInviteTeam: () => LocalizedString
		/**
		 * Concluído
		 */
		gettingStartedCompleted: () => LocalizedString
		/**
		 * Pendente
		 */
		gettingStartedPending: () => LocalizedString
		/**
		 * Bem-vindo ao Open Panel! 👋
		 */
		welcomeBannerTitle: () => LocalizedString
		/**
		 * Configure seu primeiro projeto em menos de 2 minutos.
		 */
		welcomeBannerDescription: () => LocalizedString
		/**
		 * Dispensar
		 */
		welcomeBannerDismiss: () => LocalizedString
		/**
		 * Começar Agora
		 */
		welcomeBannerGetStarted: () => LocalizedString
		/**
		 * Métricas do Sistema
		 */
		systemMetrics: () => LocalizedString
		/**
		 * Monitoramento em tempo real do seu host
		 */
		systemMetricsDescription: () => LocalizedString
		/**
		 * Mostrar Métricas
		 */
		showMetrics: () => LocalizedString
		/**
		 * Ocultar Métricas
		 */
		hideMetrics: () => LocalizedString
	}
	appTitles: {
		/**
		 * Dashboard
		 */
		dashboard: () => LocalizedString
		/**
		 * Monitor do Sistema
		 */
		systemMonitor: () => LocalizedString
		/**
		 * Configurações do Sistema
		 */
		systemSettings: () => LocalizedString
		/**
		 * Gerenciamento de Identidade
		 */
		identityManagement: () => LocalizedString
		/**
		 * Backup & Recuperação
		 */
		backupRecovery: () => LocalizedString
		/**
		 * Projetos
		 */
		projects: () => LocalizedString
		/**
		 * Segurança & Logs
		 */
		securityLogs: () => LocalizedString
		/**
		 * Painel
		 */
		panel: () => LocalizedString
		/**
		 * Perfil do Usuário
		 */
		profile: () => LocalizedString
	}
	profile: {
		/**
		 * Seu Perfil
		 */
		title: () => LocalizedString
		/**
		 * Gerencie suas informações pessoais e segurança
		 */
		subtitle: () => LocalizedString
		/**
		 * Informações Básicas
		 */
		basicInfo: () => LocalizedString
		/**
		 * Segurança
		 */
		security: () => LocalizedString
		/**
		 * Alterar Senha
		 */
		changePassword: () => LocalizedString
		/**
		 * Autenticação de Dois Fatores
		 */
		twoFactorAuth: () => LocalizedString
		/**
		 * Adicione uma camada extra de segurança à sua conta.
		 */
		twoFactorDesc: () => LocalizedString
		/**
		 * Sessões Ativas
		 */
		sessions: () => LocalizedString
	}
	projectDetails: {
		/**
		 * Adicionar Serviço
		 */
		addService: () => LocalizedString
		/**
		 * Criar Novo Serviço
		 */
		createNewService: () => LocalizedString
		/**
		 * Nome do Serviço
		 */
		serviceName: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
		/**
		 * Imagem / Tipo
		 */
		imageType: () => LocalizedString
		/**
		 * Recursos
		 */
		resources: () => LocalizedString
		/**
		 * Rede
		 */
		networking: () => LocalizedString
		/**
		 * Ações
		 */
		actions: () => LocalizedString
	}
	security: {
		/**
		 * Exportar Logs
		 */
		exportLogs: () => LocalizedString
		/**
		 * Exportando logs
		 */
		exportingLogs: () => LocalizedString
		/**
		 * Preparando arquivo CSV...
		 */
		preparingCsv: () => LocalizedString
		/**
		 * Logs exportados com sucesso!
		 */
		exportSuccess: () => LocalizedString
		/**
		 * Erro ao exportar logs
		 */
		exportError: () => LocalizedString
		/**
		 * Analisar Logs
		 */
		analyzeLogs: () => LocalizedString
		/**
		 * Analisando...
		 */
		analyzing: () => LocalizedString
		/**
		 * Timestamp
		 */
		timestamp: () => LocalizedString
		/**
		 * Ação
		 */
		action: () => LocalizedString
		/**
		 * Email do Usuário
		 */
		userEmail: () => LocalizedString
		/**
		 * ID do Usuário
		 */
		userId: () => LocalizedString
		/**
		 * Recurso Alvo
		 */
		targetResource: () => LocalizedString
		/**
		 * Endereço IP
		 */
		ipAddress: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
	}
	serviceDetail: {
		/**
		 * Serviços do Projeto
		 */
		projectServices: () => LocalizedString
		/**
		 * Visão Geral
		 */
		overview: () => LocalizedString
		/**
		 * Variáveis de Ambiente
		 */
		environment: () => LocalizedString
		/**
		 * Rede
		 */
		networking: () => LocalizedString
		/**
		 * Métricas
		 */
		metrics: () => LocalizedString
		/**
		 * Logs
		 */
		logs: () => LocalizedString
		/**
		 * Implantações
		 */
		deployments: () => LocalizedString
		/**
		 * Avançado
		 */
		advanced: () => LocalizedString
		/**
		 * Conexão
		 */
		credentials: () => LocalizedString
		/**
		 * Backups
		 */
		backups: () => LocalizedString
		/**
		 * Console
		 */
		console: () => LocalizedString
		/**
		 * Parar
		 */
		stop: () => LocalizedString
		/**
		 * Parando...
		 */
		stopping: () => LocalizedString
		/**
		 * Iniciar
		 */
		start: () => LocalizedString
		/**
		 * Iniciando...
		 */
		starting: () => LocalizedString
		/**
		 * Reiniciar
		 */
		restart: () => LocalizedString
		/**
		 * Reiniciando...
		 */
		restarting: () => LocalizedString
		/**
		 * Implantar
		 */
		deploy: () => LocalizedString
		/**
		 * Serviço Reiniciado
		 */
		serviceRestarted: () => LocalizedString
		/**
		 * {name} reiniciado com sucesso. ID do Container: {containerId}
		 */
		serviceRestartedMessage: (arg: { containerId: string, name: string }) => LocalizedString
		/**
		 * Falha ao Reiniciar
		 */
		restartFailed: () => LocalizedString
		/**
		 * Serviço Iniciado
		 */
		serviceStarted: () => LocalizedString
		/**
		 * {name} foi iniciado com sucesso
		 */
		serviceStartedMessage: (arg: { name: string }) => LocalizedString
		/**
		 * Falha ao Iniciar
		 */
		startFailed: () => LocalizedString
		/**
		 * Serviço Parado
		 */
		serviceStopped: () => LocalizedString
		/**
		 * {name} foi parado com sucesso
		 */
		serviceStoppedMessage: (arg: { name: string }) => LocalizedString
		/**
		 * Falha ao Parar
		 */
		stopFailed: () => LocalizedString
		/**
		 * Implantação Iniciada
		 */
		deploymentTriggered: () => LocalizedString
		/**
		 * Nova implantação iniciada para {name}
		 */
		deploymentTriggeredMessage: (arg: { name: string }) => LocalizedString
		/**
		 * Falha na Implantação
		 */
		deployFailed: () => LocalizedString
		/**
		 * Logs do Container
		 */
		containerLogs: () => LocalizedString
		/**
		 * Nenhum log disponível. Os logs aparecerão aqui quando o serviço estiver em execução.
		 */
		noLogsAvailable: () => LocalizedString
		/**
		 * Nome de Usuário
		 */
		username: () => LocalizedString
		/**
		 * Senha
		 */
		password: () => LocalizedString
		/**
		 * Nome do Banco de Dados
		 */
		databaseName: () => LocalizedString
		/**
		 * Host Interno
		 */
		internalHost: () => LocalizedString
		/**
		 * Porta Interna
		 */
		internalPort: () => LocalizedString
		/**
		 * String de Conexão
		 */
		connectionString: () => LocalizedString
		/**
		 * Zona de Perigo
		 */
		dangerZone: () => LocalizedString
		/**
		 * Ações irreversíveis que afetam a disponibilidade do seu serviço.
		 */
		dangerZoneDesc: () => LocalizedString
		/**
		 * Excluir Serviço
		 */
		deleteService: () => LocalizedString
		/**
		 * Tem certeza que deseja excluir este serviço? Esta ação não pode ser desfeita.
		 */
		deleteServiceConfirm: () => LocalizedString
		/**
		 * Forçar Reconstrução
		 */
		forceRebuild: () => LocalizedString
		/**
		 * Forçar reconstrução?
		 */
		forceRebuildConfirm: () => LocalizedString
		/**
		 * Reconstrução iniciada
		 */
		rebuildTriggered: () => LocalizedString
		/**
		 * Alterações salvas
		 */
		changesSaved: () => LocalizedString
		/**
		 * Falha ao salvar alterações
		 */
		failedToSave: () => LocalizedString
		/**
		 * Falha ao excluir serviço
		 */
		failedToDelete: () => LocalizedString
		/**
		 * Carregando backups...
		 */
		loadingBackups: () => LocalizedString
		/**
		 * Nenhum backup encontrado.
		 */
		noBackupsFound: () => LocalizedString
		/**
		 * Restaurar Backup
		 */
		restoreBackup: () => LocalizedString
		/**
		 * Tem certeza que deseja restaurar este backup? Isso substituirá o banco de dados atual.
		 */
		restoreBackupConfirm: () => LocalizedString
		/**
		 * Excluir Backup
		 */
		deleteBackup: () => LocalizedString
		/**
		 * Tem certeza que deseja excluir este backup? Esta ação não pode ser desfeita.
		 */
		deleteBackupConfirm: () => LocalizedString
		/**
		 * Falha ao excluir backup
		 */
		failedToDeleteBackup: () => LocalizedString
		/**
		 * Adicionar Variável
		 */
		addVariable: () => LocalizedString
		/**
		 * Não é possível excluir variável de ambiente bloqueada
		 */
		cannotDeleteLocked: () => LocalizedString
		/**
		 * Falha ao excluir variável de ambiente
		 */
		failedToDeleteEnvVar: () => LocalizedString
		/**
		 * Todas as variáveis de ambiente devem ter uma chave
		 */
		allVarsMustHaveKey: () => LocalizedString
		/**
		 * Falha ao salvar variáveis de ambiente
		 */
		failedToSaveEnvVars: () => LocalizedString
		/**
		 * Falha ao salvar origem
		 */
		failedToSaveSource: () => LocalizedString
		/**
		 * Sem Credenciais (Repositório Público)
		 */
		noCredentialsPublicRepo: () => LocalizedString
		/**
		 * Adicionar mais credenciais em Configurações do Sistema > GitOps
		 */
		addMoreCredentials: () => LocalizedString
		/**
		 * Configuração de origem salva
		 */
		sourceConfigurationSaved: () => LocalizedString
		/**
		 * Nome do Arquivo
		 */
		filename: () => LocalizedString
		/**
		 * Tamanho
		 */
		size: () => LocalizedString
		/**
		 * Data
		 */
		date: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
		/**
		 * Ações
		 */
		actions: () => LocalizedString
		/**
		 * Restaurar
		 */
		restore: () => LocalizedString
		/**
		 * Criando...
		 */
		creating: () => LocalizedString
		/**
		 * Criar Backup
		 */
		createBackup: () => LocalizedString
		/**
		 * Atualizar Recursos
		 */
		updateResources: () => LocalizedString
		/**
		 * Atualizando...
		 */
		updating: () => LocalizedString
		/**
		 * Backup Restaurado
		 */
		backupRestored: () => LocalizedString
		/**
		 * Falha ao Restaurar
		 */
		restoreFailed: () => LocalizedString
		/**
		 * Backup Excluído
		 */
		backupDeleted: () => LocalizedString
		/**
		 * Falha ao Excluir
		 */
		deleteFailed: () => LocalizedString
	}
	serviceModal: {
		/**
		 * Criar Novo Serviço
		 */
		createNewService: () => LocalizedString
		/**
		 * Passo {step} de {total}
		 */
		stepXofY: (arg: { step: number, total: number }) => LocalizedString
		/**
		 * Escolher Tipo
		 */
		chooseType: () => LocalizedString
		/**
		 * Configurar
		 */
		configure: () => LocalizedString
		/**
		 * Revisar e Criar
		 */
		reviewCreate: () => LocalizedString
		/**
		 * Aplicação
		 */
		application: () => LocalizedString
		/**
		 * Implante aplicações web, APIs ou microsserviços a partir de imagens Docker ou repositórios Git
		 */
		applicationDesc: () => LocalizedString
		/**
		 * Banco de Dados
		 */
		database: () => LocalizedString
		/**
		 * PostgreSQL, MySQL, MongoDB ou Redis com configuração automática
		 */
		databaseDesc: () => LocalizedString
		/**
		 * Imagem Docker
		 */
		dockerImage: () => LocalizedString
		/**
		 * Use uma imagem Docker pré-construída do DockerHub ou um registro
		 */
		dockerImageDesc: () => LocalizedString
		/**
		 * Repositório Git
		 */
		gitRepository: () => LocalizedString
		/**
		 * Construa e implante a partir do seu repositório GitHub, GitLab ou Bitbucket
		 */
		gitRepositoryDesc: () => LocalizedString
		/**
		 * Voltar
		 */
		back: () => LocalizedString
		/**
		 * Próximo
		 */
		next: () => LocalizedString
		/**
		 * Cancelar
		 */
		cancel: () => LocalizedString
		/**
		 * Criar Serviço
		 */
		createService: () => LocalizedString
		/**
		 * Criando...
		 */
		creating: () => LocalizedString
		/**
		 * Criado!
		 */
		created: () => LocalizedString
		/**
		 * Nome do Serviço
		 */
		serviceName: () => LocalizedString
		/**
		 * meu-servico
		 */
		serviceNamePlaceholder: () => LocalizedString
		/**
		 * Apenas letras minúsculas, números e hífens
		 */
		serviceNameHint: () => LocalizedString
		/**
		 * Imagem Docker
		 */
		dockerImageLabel: () => LocalizedString
		/**
		 * nginx:latest
		 */
		dockerImagePlaceholder: () => LocalizedString
		/**
		 * Porta Interna
		 */
		internalPort: () => LocalizedString
		/**
		 * 3000
		 */
		internalPortPlaceholder: () => LocalizedString
		/**
		 * Porta Exposta (Opcional)
		 */
		exposedPort: () => LocalizedString
		/**
		 * 8080
		 */
		exposedPortPlaceholder: () => LocalizedString
		/**
		 * Estratégia de Implantação
		 */
		deploymentStrategy: () => LocalizedString
		/**
		 * URL do Repositório
		 */
		repositoryUrl: () => LocalizedString
		/**
		 * https://github.com/usuario/repo.git
		 */
		repositoryUrlPlaceholder: () => LocalizedString
		/**
		 * Branch
		 */
		branch: () => LocalizedString
		/**
		 * main
		 */
		branchPlaceholder: () => LocalizedString
		/**
		 * Selecionar Tipo de Banco de Dados
		 */
		selectDatabaseType: () => LocalizedString
		/**
		 * Configuração do Banco de Dados
		 */
		databaseConfiguration: () => LocalizedString
		/**
		 * Tipo
		 */
		type: () => LocalizedString
		/**
		 * Versão
		 */
		version: () => LocalizedString
		/**
		 * Nome de Usuário
		 */
		username: () => LocalizedString
		/**
		 * A senha será gerada automaticamente e exibida após a criação
		 */
		passwordGenerated: () => LocalizedString
		/**
		 * Nome do serviço é obrigatório
		 */
		nameRequired: () => LocalizedString
		/**
		 * O nome deve ter pelo menos 3 caracteres
		 */
		nameMinLength: () => LocalizedString
		/**
		 * O nome pode conter apenas letras minúsculas, números e hífens
		 */
		nameInvalid: () => LocalizedString
		/**
		 * Já existe um serviço com este nome
		 */
		nameExists: () => LocalizedString
		/**
		 * Imagem Docker é obrigatória
		 */
		dockerImageRequired: () => LocalizedString
		/**
		 * URL do repositório é obrigatória
		 */
		repositoryRequired: () => LocalizedString
		/**
		 * Porta interna é obrigatória
		 */
		portRequired: () => LocalizedString
		/**
		 * Serviço criado com sucesso!
		 */
		serviceCreatedSuccess: () => LocalizedString
		/**
		 * Falha ao criar serviço
		 */
		createError: () => LocalizedString
		/**
		 * PostgreSQL
		 */
		postgres: () => LocalizedString
		/**
		 * MySQL
		 */
		mysql: () => LocalizedString
		/**
		 * MongoDB
		 */
		mongodb: () => LocalizedString
		/**
		 * Redis
		 */
		redis: () => LocalizedString
	}
}

export type Formatters = {}
