/* eslint-disable */
// @ts-nocheck
// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.

import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt-BR'
export type Locales = 'pt-BR' | 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		loading: string
		error: string
		success: string
		save: string
		cancel: string
		delete: string
		edit: string
		close: string
		back: string
		next: string
		finish: string
		email: string
		password: string
		name: string
		logout: string
		irreversible: string
	}
	auth: {
		login: string
		loginTitle: string
		loginSubtitle: string
		emailPlaceholder: string
		passwordPlaceholder: string
		invalidCredentials: string
		loginSuccess: string
		logoutSuccess: string
		rememberMe: string
	}
	onboarding: {
		title: string
		subtitle: string
		step1: {
			title: string
			light: string
			dark: string
			lightEmoji: string
			darkEmoji: string
		}
		step2: {
			title: string
			subtitle: string
			apiKeyPlaceholder: string
			urlPlaceholder: string
			validate: string
			validateConnection: string
			defaultProvider: string
			selectDefault: string
			validating: RequiredParams<'provider'>
			validationSuccess: RequiredParams<'provider'>
			validationError: RequiredParams<'provider' | 'error'>
			ollamaNote: string
			providers: {
				gemini: {
					name: string
					description: string
					helpText: string
				}
				claude: {
					name: string
					description: string
					helpText: string
				}
				github: {
					name: string
					description: string
					helpText: string
				}
				ollama: {
					name: string
					description: string
					helpText: string
				}
			}
		}
		step3: {
			title: string
			subtitle: string
			newPassword: string
			newPasswordPlaceholder: string
			confirmPassword: string
			confirmPasswordPlaceholder: string
			passwordStrength: string
			strengthWeak: string
			strengthMedium: string
			strengthStrong: string
			strengthVeryStrong: string
			requirements: {
				minLength: string
				uppercase: string
				lowercase: string
				number: string
				special: string
			}
			warning: string
		}
		complete: string
		completing: string
		footer: string
		errors: {
			passwordMismatch: string
			passwordTooShort: string
			passwordWeak: string
			passwordRequired: string
			noProvider: string
			noDefaultProvider: string
			completionFailed: string
		}
		success: string
	}
	dashboard: {
		title: string
		welcome: RequiredParams<'name'>
		projects: string
		containers: string
		deployments: string
		activeProjects: string
		manageApplications: string
		createProject: string
		searchProjects: string
		gridView: string
		listView: string
		noProjectsFound: string
		noProjectsMatching: RequiredParams<'search'>
		createFirstProject: string
		addMonitoringCard: string
		hostCpuLoad: string
		hostRam: string
		storage: string
		ingressTraffic: string
		used: string
		free: string
		avg: string
		noDataAvailable: string
	}
	projects: {
		title: string
		create: string
		noProjects: string
		status: {
			active: string
			paused: string
			error: string
			deploying: string
			stopped: string
		}
		deleteProjectTitle: string
		deleteProjectMessage: string
		deleteSuccess: string
		deleteSuccessMessage: RequiredParams<'name'>
		deleteError: string
		editProjectTitle: string
		editProjectSuccess: string
		editProjectSuccessMessage: RequiredParams<'name'>
		editProjectError: string
		createSuccess: string
		createSuccessMessage: RequiredParams<'name'>
	}
	settings: {
		title: string
		profile: string
		security: string
		aiProviders: string
		theme: string
		language: string
		changePassword: string
		currentPassword: string
		passwordChanged: string
	}
	errors: {
		generic: string
		network: string
		unauthorized: string
		notFound: string
		validation: string
	}
	validation: {
		required: RequiredParams<'field'>
		email: string
		minLength: RequiredParams<'field' | 'min'>
		maxLength: RequiredParams<'field' | 'max'>
	}
	header: {
		search: string
		searchPlaceholder: string
		notifications: string
		markAllRead: string
		noNotifications: string
		toggleMenu: string
		userMenu: string
		profileSettings: string
		preferences: string
		signOut: string
		administrator: string
	}
	sidebar: {
		infrastructure: string
		cluster: string
		monitoring: string
		identity: string
		security: string
		backups: string
		settings: string
		expandSidebar: string
		collapseSidebar: string
		menu: string
	}
	appTitles: {
		dashboard: string
		systemMonitor: string
		systemSettings: string
		identityManagement: string
		backupRecovery: string
		projects: string
		securityLogs: string
		panel: string
	}
}

export type TranslationFunctions = {
	common: {
		loading: () => LocalizedString
		error: () => LocalizedString
		success: () => LocalizedString
		save: () => LocalizedString
		cancel: () => LocalizedString
		delete: () => LocalizedString
		edit: () => LocalizedString
		close: () => LocalizedString
		back: () => LocalizedString
		next: () => LocalizedString
		finish: () => LocalizedString
		email: () => LocalizedString
		password: () => LocalizedString
		name: () => LocalizedString
		logout: () => LocalizedString
		irreversible: () => LocalizedString
	}
	auth: {
		login: () => LocalizedString
		loginTitle: () => LocalizedString
		loginSubtitle: () => LocalizedString
		emailPlaceholder: () => LocalizedString
		passwordPlaceholder: () => LocalizedString
		invalidCredentials: () => LocalizedString
		loginSuccess: () => LocalizedString
		logoutSuccess: () => LocalizedString
		rememberMe: () => LocalizedString
	}
	onboarding: {
		title: () => LocalizedString
		subtitle: () => LocalizedString
		step1: {
			title: () => LocalizedString
			light: () => LocalizedString
			dark: () => LocalizedString
			lightEmoji: () => LocalizedString
			darkEmoji: () => LocalizedString
		}
		step2: {
			title: () => LocalizedString
			subtitle: () => LocalizedString
			apiKeyPlaceholder: () => LocalizedString
			urlPlaceholder: () => LocalizedString
			validate: () => LocalizedString
			validateConnection: () => LocalizedString
			defaultProvider: () => LocalizedString
			selectDefault: () => LocalizedString
			validating: (arg: { provider: string }) => LocalizedString
			validationSuccess: (arg: { provider: string }) => LocalizedString
			validationError: (arg: { provider: string; error: string }) => LocalizedString
			ollamaNote: () => LocalizedString
			providers: {
				gemini: {
					name: () => LocalizedString
					description: () => LocalizedString
					helpText: () => LocalizedString
				}
				claude: {
					name: () => LocalizedString
					description: () => LocalizedString
					helpText: () => LocalizedString
				}
				github: {
					name: () => LocalizedString
					description: () => LocalizedString
					helpText: () => LocalizedString
				}
				ollama: {
					name: () => LocalizedString
					description: () => LocalizedString
					helpText: () => LocalizedString
				}
			}
		}
		step3: {
			title: () => LocalizedString
			subtitle: () => LocalizedString
			newPassword: () => LocalizedString
			newPasswordPlaceholder: () => LocalizedString
			confirmPassword: () => LocalizedString
			confirmPasswordPlaceholder: () => LocalizedString
			passwordStrength: () => LocalizedString
			strengthWeak: () => LocalizedString
			strengthMedium: () => LocalizedString
			strengthStrong: () => LocalizedString
			strengthVeryStrong: () => LocalizedString
			requirements: {
				minLength: () => LocalizedString
				uppercase: () => LocalizedString
				lowercase: () => LocalizedString
				number: () => LocalizedString
				special: () => LocalizedString
			}
			warning: () => LocalizedString
		}
		complete: () => LocalizedString
		completing: () => LocalizedString
		footer: () => LocalizedString
		errors: {
			passwordMismatch: () => LocalizedString
			passwordTooShort: () => LocalizedString
			passwordWeak: () => LocalizedString
			passwordRequired: () => LocalizedString
			noProvider: () => LocalizedString
			noDefaultProvider: () => LocalizedString
			completionFailed: () => LocalizedString
		}
		success: () => LocalizedString
	}
	dashboard: {
		title: () => LocalizedString
		welcome: (arg: { name: string }) => LocalizedString
		projects: () => LocalizedString
		containers: () => LocalizedString
		deployments: () => LocalizedString
		activeProjects: () => LocalizedString
		manageApplications: () => LocalizedString
		createProject: () => LocalizedString
		searchProjects: () => LocalizedString
		gridView: () => LocalizedString
		listView: () => LocalizedString
		noProjectsFound: () => LocalizedString
		noProjectsMatching: (arg: { search: string }) => LocalizedString
		createFirstProject: () => LocalizedString
		addMonitoringCard: () => LocalizedString
		hostCpuLoad: () => LocalizedString
		hostRam: () => LocalizedString
		storage: () => LocalizedString
		ingressTraffic: () => LocalizedString
		used: () => LocalizedString
		free: () => LocalizedString
		avg: () => LocalizedString
		noDataAvailable: () => LocalizedString
	}
	projects: {
		title: () => LocalizedString
		create: () => LocalizedString
		noProjects: () => LocalizedString
		status: {
			active: () => LocalizedString
			paused: () => LocalizedString
			error: () => LocalizedString
			deploying: () => LocalizedString
			stopped: () => LocalizedString
		}
		deleteProjectTitle: () => LocalizedString
		deleteProjectMessage: () => LocalizedString
		deleteSuccess: () => LocalizedString
		deleteSuccessMessage: (arg: { name: string }) => LocalizedString
		deleteError: () => LocalizedString
		editProjectTitle: () => LocalizedString
		editProjectSuccess: () => LocalizedString
		editProjectSuccessMessage: (arg: { name: string }) => LocalizedString
		editProjectError: () => LocalizedString
		createSuccess: () => LocalizedString
		createSuccessMessage: (arg: { name: string }) => LocalizedString
	}
	settings: {
		title: () => LocalizedString
		profile: () => LocalizedString
		security: () => LocalizedString
		aiProviders: () => LocalizedString
		theme: () => LocalizedString
		language: () => LocalizedString
		changePassword: () => LocalizedString
		currentPassword: () => LocalizedString
		passwordChanged: () => LocalizedString
	}
	errors: {
		generic: () => LocalizedString
		network: () => LocalizedString
		unauthorized: () => LocalizedString
		notFound: () => LocalizedString
		validation: () => LocalizedString
	}
	validation: {
		required: (arg: { field: string }) => LocalizedString
		email: () => LocalizedString
		minLength: (arg: { field: string; min: number }) => LocalizedString
		maxLength: (arg: { field: string; max: number }) => LocalizedString
	}
	header: {
		search: () => LocalizedString
		searchPlaceholder: () => LocalizedString
		notifications: () => LocalizedString
		markAllRead: () => LocalizedString
		noNotifications: () => LocalizedString
		toggleMenu: () => LocalizedString
		userMenu: () => LocalizedString
		profileSettings: () => LocalizedString
		preferences: () => LocalizedString
		signOut: () => LocalizedString
		administrator: () => LocalizedString
	}
	sidebar: {
		infrastructure: () => LocalizedString
		cluster: () => LocalizedString
		monitoring: () => LocalizedString
		identity: () => LocalizedString
		security: () => LocalizedString
		backups: () => LocalizedString
		settings: () => LocalizedString
		expandSidebar: () => LocalizedString
		collapseSidebar: () => LocalizedString
		menu: () => LocalizedString
	}
	dashboard: {
		activeProjects: () => LocalizedString
		manageApplications: () => LocalizedString
		createProject: () => LocalizedString
		searchProjects: () => LocalizedString
		gridView: () => LocalizedString
		listView: () => LocalizedString
		noProjectsFound: () => LocalizedString
		noProjectsMatching: (arg: { search: string }) => LocalizedString
		createFirstProject: () => LocalizedString
		addMonitoringCard: () => LocalizedString
		hostCpuLoad: () => LocalizedString
		hostRam: () => LocalizedString
		storage: () => LocalizedString
		ingressTraffic: () => LocalizedString
		used: () => LocalizedString
		free: () => LocalizedString
		avg: () => LocalizedString
		noDataAvailable: () => LocalizedString
	}
	appTitles: {
		dashboard: () => LocalizedString
		systemMonitor: () => LocalizedString
		systemSettings: () => LocalizedString
		identityManagement: () => LocalizedString
		backupRecovery: () => LocalizedString
		projects: () => LocalizedString
		securityLogs: () => LocalizedString
		panel: () => LocalizedString
	}
}

export type Formatters = {}
